### ISSUE TITLE
Size of Input Images for Using Pre-Trained Model

### ISSUE THREAD

**Issue by ahkarami** [layumi/Person_reID_baseline_pytorch#10]
Dear @layumi,
Thank you for your nice work. I have a question. What is the correct size of input image, If one want to use your released pre-trained model (_i.e._, for forward pass & feature extraction of input image)? I mean (256,128) or (288,144)?

**Comment by layumi** [comment]
Hi @ahkarami 
When training, we crop (256,144) from (288,144).
When testing, since we have global pooling, directly using (288,144) can yield the better performance.

**Comment by ahkarami** [comment]
Thank you.
