### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by Jamence** [layumi/Person_reID_baseline_pytorch#100]
Can I run with CPU only ?

**Comment by Chang-shuaishuai** [comment]
请问现在有cpu版本了吗？？

**Comment by layumi** [comment]
Hi @Chang-shuaishuai 

You may check https://github.com/layumi/Person_reID_baseline_pytorch/tree/master/colab to use free gpu on Google Colab.

**Comment by Chang-shuaishuai** [comment]
好的，谢谢大佬
