### ISSUE TITLE
Error(s) in loading state_dict for ft_net

### ISSUE THREAD

**Issue by muna-cs** [layumi/Person_reID_baseline_pytorch#103]
I get this error when run test.py

> RuntimeError: Error(s) in loading state_dict for ft_net:
> 	size mismatch for classifier.classifier.0.weight: copying a param with shape torch.Size([156, 512]) from checkpoint, the shape in current model is torch.Size([751, 512]).
> 	size mismatch for classifier.classifier.0.bias: copying a param with shape torch.Size([156]) from checkpoint, the shape in current model is torch.Size([751]).

How can I fix this error ?

**Comment by layumi** [comment]
It seems that you have 156 classes while training.
Please change your https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L201 751 to 156.
