### ISSUE TITLE
Missing imports in ./prepare_static.py?

### ISSUE THREAD

**Issue by cclauss** [layumi/Person_reID_baseline_pytorch#105]
[flake8](http://flake8.pycqa.org) testing of https://github.com/layumi/Person_reID_baseline_pytorch on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./prepare_static.py:31:9: F821 undefined name 'transforms'
        transforms.Resize((288,144), interpolation=3),
        ^
./prepare_static.py:34:9: F821 undefined name 'transforms'
        transforms.ToTensor(),
        ^
./prepare_static.py:39:9: F821 undefined name 'transforms'
        transforms.Resize(size=(256,128),interpolation=3), #Image.BICUBIC
        ^
./prepare_static.py:40:9: F821 undefined name 'transforms'
        transforms.ToTensor(),
        ^
./prepare_static.py:41:9: F821 undefined name 'transforms'
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
        ^
./prepare_static.py:47:14: F821 undefined name 'transforms'
    'train': transforms.Compose( transform_train_list ),
             ^
./prepare_static.py:48:12: F821 undefined name 'transforms'
    'val': transforms.Compose(transform_val_list),
           ^
./prepare_static.py:57:27: F821 undefined name 'datasets'
image_datasets['train'] = datasets.ImageFolder(os.path.join(data_dir, 'train' + train_all),
                          ^
./prepare_static.py:59:25: F821 undefined name 'datasets'
image_datasets['val'] = datasets.ImageFolder(os.path.join(data_dir, 'val'),
                        ^
9     F821 undefined name 'transforms'
9
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by layumi** [comment]
Thank you @cclauss 
I think I miss the `from torchvision import datasets, transforms`
