### ISSUE TITLE
when I run test.py,it show that 'Sequential' object has no attribute 'model'

### ISSUE THREAD

**Issue by wting861006** [layumi/Person_reID_baseline_pytorch#108]
C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\ImgFeature\person_reid\Person_reID_baseline_pytorch-master>python test.py --name PCB-64
-------test-----------
Traceback (most recent call last):
  File "test.py", line 213, in <module>
    model = PCB_test(model)
  File "C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\ImgFeature\person_reid\Person_reID_baseline_pytorch-master\model.py", line 191, in __init_
_
    self.model = model.model
  File "C:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'model'

operation system:windows 10
python:3.6
torch:1.0.1

**Comment by dyh127** [comment]
It seems your model is loaded incorrectly, have checked the path of your model? and I see that your parameter is 'PCB-64'  which should be 'PCB' in original code, so have you changed in some place, please show me, thank you, and another question, I see your operation system is windows 10, so do you run code at CPU?

**Comment by wting861006** [comment]
@dyh127 Hi.I will try as you say again later.I run code at nvidia-1080ti.

**Comment by layumi** [comment]
@wting861006 
Do you use `fp16`?

**Comment by layumi** [comment]
I have fixed it. @wting861006  You may refer to https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L212-L223

**Comment by wting861006** [comment]
@layumi It work.Thinks for help.

**Comment by wting861006** [comment]
@layumi It work.Thanks for help.
