### ISSUE TITLE
测试是否提取了Gallery里面0000的结果

### ISSUE THREAD

**Issue by BulimiaDH** [layumi/Person_reID_baseline_pytorch#109]
因为我看见Gallery 里面label为0000的也被算进去计算了，这个不应该是junk data吗，我看代码里面只排除了label为-1的id

**Comment by layumi** [comment]
0000是一些dpm错误监测到的背景，作为distractor，还是放到gallery中的。 但是-1的多为正确行人的一部分，或者比较远景，故而在测试时排除。
