### ISSUE TITLE
Other ConvNets as the Backbone

### ISSUE THREAD

**Issue by ahkarami** [layumi/Person_reID_baseline_pytorch#11]
Dear @layumi,
Have you ever trained other ConvNets (_e.g._, ResNet101, ResNet152, ResNext, Inception-ResNet-V2) as the backbone of your code?

**Comment by layumi** [comment]
Hi @ahkarami 
I haven't trained other convnets. But I think this code can be converted to trian them.
You mainly need to change the code in the `model.py`.

**Comment by ahkarami** [comment]
Dear @layumi,
Thank you for your answer. I also appreciate you for adding `DenseNet-121` to `model.py`. I encourage you to add other models (_e.g.,_ ResNext, DualPathNet, Inception-ResNet-V2, ...). You can use the below link for other models:
[Pre-Trained Models on PyTorch](https://github.com/Cadene/pretrained-models.pytorch)
At last, it would be great if you release the weights of your trained models (e.g., DenseNet-121).
Thank you very much.

**Comment by layumi** [comment]
Thank you for your suggestions, @ahkarami 
For the time being, I may not add more models. 
The main reason is that ResNet-50 is a common choice in most academic papers.
I want to keep this repos simple and it can be in a fair comparison with other methods.

P.S. The Dense121 model can be found at [Here](https://drive.google.com/file/d/1NgZWnYBCzESgKNzLeoWUMxggZ6SSEaZL) .
I just uploaded it. Many thanks.

**Comment by ahkarami** [comment]
Dear @layumi,
Thank you very much for your complete answer. Yes, I agree with you there. ResNet50 is a common choice and great as a baseline model.
