### ISSUE TITLE
A problem when calculating mAP

### ISSUE THREAD

**Issue by RayHY** [layumi/Person_reID_baseline_pytorch#110]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/a253943e16abd94277ee832a950b975df75b11e3/evaluate.py#L47-L54

In the above code, I can't understand the way to calculate `old_precision`. Here `old_precision` should be the precison of the last true-match, should it be changed like this?
`old_precision = i*1.0/(rows_good[i-1] +1)`
or just 
```python
...
ap = ap + d_recall*(old_precision + precision)/2 
# Simplified from here `http://www.robots.ox.ac.uk/~vgg/data/oxbuildings/compute_ap.cpp`
old_precision = precision
```

**Comment by RayHY** [comment]
simple test:
```python
import numpy as np

score = [0.6, 0.8, 0.1, 0.9, 0.2]
index = np.argsort(score)[::-1]
good_index = [3, 0]

ngood = len(good_index)
mask = np.in1d(index, good_index)
rows_good = np.argwhere(mask==True)
rows_good = rows_good.flatten()
print("index:", index)
print("good_index:", good_index)
print("\nrows_good:", rows_good)
```

```output
index: [3 1 0 4 2]
good_index: [3, 0]

rows_good: [0 2]
```
origin way
```python
ap = 0
for i in range(ngood): 
    d_recall = 1.0/ngood 
    precision = (i+1)*1.0/(rows_good[i]+1) 
    if rows_good[i]!=0: 
        old_precision = i*1.0/rows_good[i] 
    else: 
        old_precision=1.0
    print("{0} (old_precision, precision) = ({1}, {2})".format(i, old_precision, precision))
    ap = ap + d_recall*(old_precision + precision)/2
print("ap:", ap)
```

```output
0 (old_precision, precision) = (1.0, 1.0)
1 (old_precision, precision) = (0.5, 0.6666666666666666)
ap: 0.7916666666666666
```
way1
```python
ap = 0
for i in range(ngood): 
    d_recall = 1.0/ngood 
    precision = (i+1)*1.0/(rows_good[i]+1) 
    if rows_good[i]!=0: 
        old_precision = i*1.0/(rows_good[i-1]+1)
    else: 
        old_precision=1.0
    print("{0} (old_precision, precision) = ({1}, {2})".format(i, old_precision, precision))
    ap = ap + d_recall*(old_precision + precision)/2
print("ap:", ap)
```

```output
0 (old_precision, precision) = (1.0, 1.0)
1 (old_precision, precision) = (1.0, 0.6666666666666666)
ap: 0.9166666666666666
```
way2
```python
ap = 0
for i in range(ngood): 
    d_recall = 1.0/ngood
    if i == 0:
        precision, old_precision = (i+1)*1.0/(rows_good[i]+1), (i+1)*1.0/(rows_good[i]+1)
    else:
        precision, old_precison = (i+1)*1.0/(rows_good[i]+1), precision
    print("{0} (old_precision, precision) = ({1}, {2})".format(i, old_precision, precision))
    ap = ap + d_recall*(old_precision + precision)/2
print("ap:", ap)
```

```output
0 (old_precision, precision) = (1.0, 1.0)
1 (old_precision, precision) = (1.0, 0.6666666666666666)
ap: 0.9166666666666666
```

**Comment by layumi** [comment]
If you want to use original `for` loop, 
you should not use `for i in range(ngood)`.
You may use `for i in ngallery`.

**Comment by RayHY** [comment]
as you mentioned in https://github.com/layumi/Person_reID_baseline_pytorch/issues/85#issuecomment-442927024
**the value of mAP only changed when it meets the true-matches.**

In fact, I just want to correct your code, not using exactly same code with the original code.
`old_precision` should be  `i*1.0/(rows_good[i-1] +1)` rather than `i*1.0/rows_good[i]`, **this is my point**.

**Comment by layumi** [comment]
if `i=0` ?

**Comment by RayHY** [comment]
Sorry, I missed some boundary conditions.
We use the example above
```
index  [3 1 0 4 2]
good_index: [3, 0]
rows_good: [0 2]
```
the origin way get this
```
0 (old_precision, precision) = (1.0, 1.0)
1 (old_precision, precision) = (0.5, 0.6666666666666666)
ap: 0.7916666666666666
```
when `i=1` , origin code get wrong `old_precision` 0.5. but when `i=0`, `precision`=1, 0.5 is a wrong number.

if the number of query and gallery are large enough, origin code's result is similar to the correct result.

**Comment by layumi** [comment]
The original cpp code contains a long `for` to visit every elements  in the ranking list. So they can use `old_precision = precision`. 
**Note that precision is changing in every iteration!!!**

My python code only `for` to visit the right matches. 
Precision hasn't been updated to the new value. So old_precision not equal to the precision.
I use more directly way to assign the value.
`old_precision = i*1.0/(rows_good[i-1]+1)`

**Comment by RayHY** [comment]
I'm confused:

> I use more direct way to assign the value for the real `old_precision`.
> `old_precision = i*1.0/(rows_good[i-1]+1)`

**but**

https://github.com/layumi/Person_reID_baseline_pytorch/blob/a253943e16abd94277ee832a950b975df75b11e3/evaluate.py#L51

**Comment by RayHY** [comment]
sorry for aggressive. I'm very confused now.
I have test the example above with Market1501's MATLAB code. the result of it is the same as your code. 
Maybe I need more exercise。我现在觉得我很菜。

---
我刚写了篇关于mAP的[博客](https://lowentropy.me/blog/20190223-reid%E4%BB%BB%E5%8A%A1%E4%B8%AD%E7%9A%84cmc%E5%92%8Cmap/#average-precision)，尝试写出mAP的公式，看了公式还是不知道为什么old_precision 要赋值为`i*1.0/rows_good[i]`。您能帮忙解答一下吗...

**Comment by RayHY** [comment]
我搞懂了，不是上一个匹配点，而是上一个rank对应的点。谢谢。

**Comment by RayHY** [comment]
I make a simple picture:
![image](https://user-images.githubusercontent.com/16448529/53322790-67cc8b00-3917-11e9-9f47-6c038ade6e97.png)
I thought it should be average of point 1 and point 3, in fact we should use point 2 and point 3.
Thanks for your patience @layumi.
