### ISSUE TITLE
Questions about transfer learning

### ISSUE THREAD

**Issue by jacksonly** [layumi/Person_reID_baseline_pytorch#111]
I have a question about transfer learning or using pre-train Reid's model to inference on the new dataset. At first, I have collected unlabeled videos from many cross-cameras and run the object detection's model to extract the bounding boxes from these. Then, I want to use Reid's model to label the identity of these bounding boxes. I have read the tutorial and found that Reid's goal is to extract the discriminate features. Thus, can I use the pre-train-model to extract the feature of bounding boxes directly? (because my videos are unlabeled)

**Comment by dyh127** [comment]
Hi @jacksonly,

Just use the pre-train-model may not good enough to label the bounding boxes, because the pre-train-model is trained by different domain data. 

I suggest use some domain adaptation work in Reid, such as SPGAN, EAnet, it's better than just using pre-train-model.

**Comment by jacksonly** [comment]
Thanks for your reply, I will try these works you referred on my dataset.

**Comment by layumi** [comment]
Thank you @dyh127 
Hi @jacksonly ,
I have collected some paper at [Here](https://github.com/layumi/DukeMTMC-reID_evaluation/tree/master/State-of-the-art#transfer-learning). Most papers tried several different ways to transfer the model trained on Market to another Dataset DukeMTMC-reID. You may refer to it.
