### ISSUE TITLE
The answer to the fast questions.

### ISSUE THREAD

**Issue by JisuiWang** [layumi/Person_reID_baseline_pytorch#113]
Hi, thanks for your tutorial about the person re-identification which is very interesting and I try to learn and understand it absolutely. The fast question you set in the tutorial is elaborate and I think the answer to the questions can help me a lot. Could you please sort out the answer briefly and provide it?

**Comment by venuszhou** [comment]
So do I,  this tutorial and the codes are so magic, could you please provide the answer so we can learn further, thanks, zhedong.

**Comment by layumi** [comment]
Thank you @JisuiWang @venuszhou .

I just uploaded the answer. https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/tutorial/Answers_to_Quick_Questions.md
