### ISSUE TITLE
the performance about DukeMTMC

### ISSUE THREAD

**Issue by wangyujie413** [layumi/Person_reID_baseline_pytorch#114]
for DukeMTMC dataset, I just tuned the batchsize from 32 to 64，the performance with resnet50 is

torch.Size([2228, 2048])
Rank@1:0.823609 Rank@5:0.903501 Rank@10:0.930880 mAP:0.654376

Is it normal?

**Comment by layumi** [comment]
Hi @wangyujie413 
Did you use random erasing or other tricks? If so, it is a reasonable result.

**Comment by layumi** [comment]
More results could be found at the DukeMTMC-reID leaderboard (https://github.com/layumi/DukeMTMC-reID_evaluation/tree/master/State-of-the-art).

**Comment by wangyujie413** [comment]
Yes, i just used random erasing.
thank you
