### ISSUE TITLE
AttributeError:nodule 'apex.amp' has no attribute 'initialize'

### ISSUE THREAD

**Issue by Allen-lz** [layumi/Person_reID_baseline_pytorch#115]
作者您好！我已经安装了apex且可以使用下面的语句来使用float16进行网络计算
if fp16:
    model = network_to_half(model)
    optimizer_ft = FP16_Optimizer(optimizer_ft, static_loss_scale = 128.0)
但是使用model, optimizer_ft = amp.initialize(model, optimizer_ft, opt_level = "O1")却会报出标题中的错误，我已经导入了相关包，请问该如何解决？

**Comment by Allen-lz** [comment]
network_to_half(l)怎么才同时在一次训练中对两个网络上使用

**Comment by layumi** [comment]
@Allen-lz 

要么用 network_to_half (这是apex old api)
要么用 amp （这是apex new api，我在这个repo里面已经使用amp了）

我推荐使用amp
记得不要同时用这两个api；另外可以的话更新到最新的apex，看看错误还在么？

**Comment by Allen-lz** [comment]
好的，谢谢！我去试一试

**Comment by Allen-lz** [comment]
作者您好。我更新了apex之后可以没有之前那个错误了，但是有了以下错误：
File "train.py", line 352, in <module>
    model, optimizer_ft,tripleloss = amp.initialize(model, optimizer_ft, tripleloss, opt_level = "O1")
ValueError: not enough values to unpack (expected 3, got 2)
请问有什么办法可以使得多个网络都能降为float16呢？

**Comment by layumi** [comment]
不需要把loss放到 amp 里面吧。
model, optimizer_ft = amp.initialize(model, optimizer_ft, opt_level = "O1")

**Comment by Allen-lz** [comment]
tripleloss是我自己另外加的一个继承了nn.Module的网络，只是名字带loss而已....

**Comment by layumi** [comment]
- 尝试把两个model写到一个model 里面，或者使用pytorch的model list 看看。我不清楚会不会work。
- 用老api `model = network_to_half(model)`这个一定可以但是需要改的地方相对多一点。

**Comment by Allen-lz** [comment]
好的，谢谢！
