### ISSUE TITLE
Why times loss with batch size?

### ISSUE THREAD

**Issue by BJTUJia** [layumi/Person_reID_baseline_pytorch#116]
Dear author, thanks a lot for this amazing baseline!

However, I am confused about line 229 in train.py. It seems that the loss is multiplied with batch size? Is there any reason for this operation? How is this beneficial for training?

Thanks a lot!

**Comment by layumi** [comment]
Hi @BJTUJia 
Sorry for the late response.
The loss is averaged when we backward the loss. 
To accumulate the loss items for print, we need the sum result. So I times the batchsize to get the loss sum.

**Comment by BJTUJia** [comment]
I see, thanks a lot!
