### ISSUE TITLE
Where can I get file 'pytorch_result.mat'?

### ISSUE THREAD

**Issue by dcy652701** [layumi/Person_reID_baseline_pytorch#118]
In demo.py, at 31 line,there is a code which wants to load a file called pytorch_result.mat(result = scipy.io.loadmat('pytorch_result.mat')).But I have read the tutorial and I can't find a link to download this kind of file.

**Comment by layumi** [comment]
Hi @dcy652701 
You run `test.py --name xxxxmodel` will generate the `pytorch_result.mat`.
