### ISSUE TITLE
Why my training curves looks weird?

### ISSUE THREAD

**Issue by Sibyl233** [layumi/Person_reID_baseline_pytorch#119]
![train](https://user-images.githubusercontent.com/24403298/55774073-3e7e4d80-5ac6-11e9-93ab-6b65bc39abe9.jpg)
Compared with the author's training curve:
1. Loss is high at the beginning.
2. Drop fast at early stage.
3. No cross
Did I make mistakes in setting or running?

**Comment by layumi** [comment]
It looks good if you haven't use `--train_all`.
`--train_all` will add the validation set into training, so the val curve will be much lower than the `train`.
