### ISSUE TITLE
dukemtmc4reid

### ISSUE THREAD

**Issue by aznikline** [layumi/Person_reID_baseline_pytorch#120]
Hi there, and I'm wondering whether there is a way to prepare DukeMTMC4ReID dataset ?

**Comment by layumi** [comment]
I haven't try the dataset DukeMTMC4ReID. 
DukeMTMC-reID (https://github.com/layumi/DukeMTMC-reID_evaluation) is more popular, which is using a similar naming rule with Market-1501. You can directly use the `prepare.py` to prepare the dataset.

**Comment by aznikline** [comment]
sure my network works well by following your tutorial, nice job!
but I'm still trying some new ideas on DukeMTMC4ReID, could you give me some advice?
