### ISSUE TITLE
在 prepare.py 中, 用 train set 的 每个 ID 内的第一张图片 来组成 val set ，为什么train set 和val set 可以用同样的图片？

### ISSUE THREAD

**Issue by swg209** [layumi/Person_reID_baseline_pytorch#123]
你好， prepare.py 中, 用 train set 的 每个 ID 内的第一张图片 来组成 val set ，为什么train set 和val set 可以用同样的图片？这样子的作用是什么？

**Comment by Deeplearning20** [comment]
你好，请问你弄明白了为什么“train set 和val set 可以用同样的图片”的这个问题了吗？
