### ISSUE TITLE
关于特征距离的问题

### ISSUE THREAD

**Issue by WangHonglie** [layumi/Person_reID_baseline_pytorch#129]
evaluate_gpu.py中，score=torch.mm(gf,query)，为什么score是这样算的，不应该是gf和query之间的欧式距离吗？这样不是直接两个特征的点乘结果吗？ @layumi

**Comment by layumi** [comment]
@WangHonglie  因为我把特征L2-norm过了，所以直接用了cosine距离。

**Comment by WangHonglie** [comment]
@layumi 看到了，非常感谢
