### ISSUE TITLE
model.py run error

### ISSUE THREAD

**Issue by yja1** [layumi/Person_reID_baseline_pytorch#14]
python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir your_data_path

the error is:
```
net output size:
Traceback (most recent call last):
File "/reid_baseline/model.py", line 100, in <module>
print(output.shape)
```

i want try resnet50

**Comment by layumi** [comment]
Hi @yja1 
Do you use python2?
Python3 will be fine to run the code.

**Comment by yja1** [comment]
i use pytorch 0.2  anaconda3 的 python3.6

**Comment by layumi** [comment]
Would you like to provide the whole  error log?
And you may try to update pytorch 0.3 ?

**Comment by yja1** [comment]
find.
it is pytorch edition different
print(output.data.shape)  is ok
thx~

**Comment by yja1** [comment]
if i set --use_dense false 
should i change this line to (in model.py end part):
net = ft_net(751)  # use this ?
#net = ft_net_dense(751)

**Comment by yja1** [comment]
(in model.py end part):
net = ft_net(751) # use this ?  if i use ResNet-50
#net = ft_net_dense(751) #use this ? if i use DenseNet-121 at the same time set --use_dense

**Comment by layumi** [comment]
Yes.
751 is the number of different person in Market-1501.
Since Resnet-50 and DenseNet-121 have different layer names, I write two different functions to finetune the two networks.
