### ISSUE TITLE
DukeMTMC-reID_evaluation/  /State-of-the-art/README.md

### ISSUE THREAD

**Issue by TJJTJJTJJ** [layumi/Person_reID_baseline_pytorch#141]
Hi,
   Today, I want to new performance about person Re-ID, but it lost, so is there something you can't release as you did before?

https://github.com/layumi/DukeMTMC-reID_evaluation/blob/master/State-of-the-art/README.md

Thank you

**Comment by layumi** [comment]
Hi @TJJTJJTJJ 

I am very sorry about that.
Due to the privacy concern from Duke University, DukeMTMC-reID (including pages) has to be offline.

**Comment by TJJTJJTJJ** [comment]
Thank you for your contribution. Because I have learn many things from the state-of-the-art and usually do acquire frontiers of papers on person Re-ID from the state-of-the-art. Thanks. It can be closed.

**Comment by layumi** [comment]
@TJJTJJTJJ 
https://blog.csdn.net/Layumi1993/article/details/93137996

**Comment by TJJTJJTJJ** [comment]
Perfect, you are very good. I will continue learn from you.
