### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MAdil45** [layumi/Person_reID_baseline_pytorch#142]
Hi. I have successfully trained the model but when i run the test.py to test the model then i got the following error. I trained the model on MSMT17 dataset. you have already mentioned to modify the prepare file and test file if we have to use other datasets like MSMT17. I don't know how to modify them.I am very new to this. Please can you help me out of this. Any guideline would be appreciated. 

We use the scale: 1
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    gallery_cam,gallery_label = get_id(gallery_path)
  File "test.py", line 192, in get_id
    camera = filename.split('c')[1]
IndexError: list index out of range

**Comment by layumi** [comment]
Hi @MAdil45 
MSMT has more cameras.
You may refer to a similar issue here https://github.com/layumi/Person_reID_baseline_pytorch/issues/107 (in Chinese)

In fact, you need to change this line. 
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L186

For example, camera = filename.split('c')[0:2]

**Comment by MAdil45** [comment]
Thank You so much for your response. I really appreciate that. That did solve the problem. But now i am getting this issue. I would be grateful if you look into this. 

Traceback (most recent call last):
  File "test.py", line 204, in <module>
    gallery_cam,gallery_label = get_id(gallery_path)
  File "test.py", line 198, in get_id
    camera_id.append(int(camera[0]))
ValueError: invalid literal for int() with base 10: '0819_012_11_0303afternoon_1314_1.jpg'

**Comment by MAdil45** [comment]
@layumi Kindly have a review and give me some guidelines about how to solve the above problem. I'll appreciate  your positive response.

**Comment by layumi** [comment]
```
camera = filename.split('c')[0:2]
camera_id.append(int(camera))
```

**Comment by MAdil45** [comment]
@layumi ThankYou so much Brother. I appreciate it.
