### ISSUE TITLE
KeyError: 'use_NAS'

### ISSUE THREAD

**Issue by leijuzi** [layumi/Person_reID_baseline_pytorch#143]

**Comment by layumi** [comment]
Could you provide more details?  Testing or Training induces this error.

**Comment by anilsh** [comment]
Any update? I am also getting the same error when I am using test.py. Error is following: 

This is not an error. If you want to use low precision, i.e., fp16, please install the apex with cuda support (https://github.com/NVIDIA/apex) and update pytorch to 1.0
test.py:48: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    opt.use_NAS = config['use_NAS']
KeyError: 'use_NAS'

**Comment by layumi** [comment]
If you did not use `--use_NAS` when training, you may directly set `opt.use_NAS = False`

**Comment by anilsh** [comment]
Thanks. It worked.

**Comment by yannqi** [comment]
Got it. Thanks.
