### ISSUE TITLE
How to load model weights and resume training?

### ISSUE THREAD

**Issue by Rajat-Mehta** [layumi/Person_reID_baseline_pytorch#145]
I have trained ft_net model for 60 epochs and saved the model weights after every 10 epochs. Now I want to resume training from 60th epoch and train model for 20 more epochs. I can not find any option for resuming training. 

Is there any option available for resuming training from a given epoch?

**Comment by layumi** [comment]
Hi @Rajat-Mehta 
I will consider to add this option today.
In fact, I have written `--resume` in my private repo and have not made it public.
But it might change some codes and make the `--PCB` option fail. So it takes time to verification.

**Comment by Rajat-Mehta** [comment]
Hi @layumi ,

Is --resume option available now? If yes, how to use it?

**Comment by layumi** [comment]
Hi @Rajat-Mehta 
Please check the code in developing thread (https://github.com/layumi/Person_reID_baseline_pytorch/tree/dev)
I change some API so it is a little different with the original code. 
It enable the `--resume` option and other advanced functions.

**Comment by Rajat-Mehta** [comment]
Thanks @layumi . I got the --resume option working :+1:
