### ISSUE TITLE
ImportError  : No module named torch

### ISSUE THREAD

**Issue by hljdqzr** [layumi/Person_reID_baseline_pytorch#146]
Hello,after training,when I try test it.
Error shows:
    File evalute_gpu.py,in line 2,in <module>
 import torch
ImportError  : No module named torch
But I have tried pip3 install torch /torchvision
And in python3,import torch is fine.
What can I do?Thanks!

**Comment by layumi** [comment]
You may check `which python`   `which pip`

I suggest to use anaconda.

**Comment by hljdqzr** [comment]
Thanks !
I have solved the problem.
test.py line 256:
os.system('python evaluate_gpu.py | tee -a %s'%result)
shoule be 
os.system('python3 evaluate_gpu.py | tee -a %s'%result)
Thanks again!!!
