### ISSUE TITLE
What's the memory cost for training NAS?

### ISSUE THREAD

**Issue by BJTUJia** [layumi/Person_reID_baseline_pytorch#154]
Hi, Layumi. Many thanks for this awesome repo. Can I ask how much computing resource you used to run NAS training? 

I just use your ft_net_NAS code in model.py and have downloaded the pretrained models. However, an out of memory error always occurs. I use one TITAN Xp with 12.0G memory.  How many GPUs do you use?

**Comment by layumi** [comment]
Hi @BJTUJia 

You may consider to use small batchsize, such as `16` or `8`,  with the small learning  `0.005`, `0.002`.

Note that NAS has a different mean (0.5,0.5,0.5) and std (0.5,0.5,0.5).  You need to change it.

Besides, in my experience, NAS is hard to train, which may need auxiliary classifier in the original paper. I suggest you may also try `SENet` in the feature, and `SENet` seems to be more promising.

**Comment by BJTUJia** [comment]
Hi, Layumi, many thanks for the nice tips! I will try them out!
