### ISSUE TITLE
请问在测试msmt17数据集时您使用的什么协议？

### ISSUE THREAD

**Issue by ln23415** [layumi/Person_reID_baseline_pytorch#158]
你好，十分感谢您们的工作，我想问下你们在测试msmt17数据集时您使用的什么评估协议？我看到有其他伙伴有使用名为“MSMT17_V2”的数据集，它和普通MSMT17数据集有什么关系吗？

**Comment by layumi** [comment]
我当时使用的是 MSMT17_V1 .V2和V1的区别在于是否把人脸抹除。

**Comment by ln23415** [comment]
好的谢谢~请问现在MSMT17_V2有公开下载地址吗？

**Comment by layumi** [comment]
You may contact with Prof. Shiliang Zhang https://www.pkuvmc.com/

**Comment by ln23415** [comment]
好的，谢谢
