### ISSUE TITLE
About evaluation metric

### ISSUE THREAD

**Issue by kentangSJTU** [layumi/Person_reID_baseline_pytorch#16]
Hello sir,
  First thanks a lot for the great implementation, it is really a strong baseline!
  Then, after studying your code, I have a doubt about the evaluation metric. You wrote in evaluate.py that:
```python
for i in range(ngood):
        d_recall = 1.0/ngood
        precision = (i+1)*1.0/(rows_good[i]+1)
        if rows_good[i]!=0:
            old_precision = i*1.0/rows_good[i]
        else:
            old_precision=1.0
        ap = ap + d_recall*(old_precision + precision)/2
```
Note in the last line, there is (old_precision+precison)/2. In my understanding of AP calculation, there shouldn't be such "old_precision" term.
For example, if there are 4 GT results retrieved at position 1,2,4,7, then AP should be (1/1+2/2+3/4+4/7)/4, right? In your implementation, the result seems not to be equal to that value(should be a little bit lower in fact). So what's the intuition behind such AP calculation mechanism and is it a custom practice in re-id evaluation?
I will be really appreciated for you answer.
Best Wishes!

**Comment by layumi** [comment]
Hi @kentangSJTU ,
Market-1501 Dataset follow the mAP calculation in Oxford 5k dataset.
You may refer to http://www.robots.ox.ac.uk/~vgg/data/oxbuildings/compute_ap.cpp

**Comment by kentangSJTU** [comment]
Thanks a lot for your timely reply! It's very kind of you~

**Comment by venuszhou** [comment]
@kentangSJTU 
hello, in compute_mAP, why do we ignore the junk_index? the code like below:
`    mask = np.in1d(index, junk_index, invert=True)`
`    index = index[mask]`
and why do like this:
`cmc[rows_good[0]:] = 1`
instead of
`cmc[rows_good] = 1`,
could you please more explanation about this? thanks a lot.

**Comment by layumi** [comment]
Hi @venuszhou ,

The physical meaning of CMC is whether the true matches appear before Rank-K.
Therefore, if the Rank 6th image is true match,   CMC[5:] = 1. All CMC  after 5 is set to 1. (We start from zero)
