### ISSUE TITLE
how to use json

### ISSUE THREAD

**Issue by jerry-chenrb** [layumi/Person_reID_baseline_pytorch#169]
First of all, thank you for the code you provided. I have learned a lot. At present, I have trained on my own data set, but the result is not very ideal. Maybe it is the difference of data type and the clarity of data set. I hope to use a JASON file to contain some information about my vehicle date set, including its mask ,color and so on, so should i add it in which section?

**Comment by layumi** [comment]
Hi @jerry-chenrb 
So...you want to read the jason file and load the mask. Right?
I suggest that you may consider to re-write the ImageFolder. For example, you may refer to https://github.com/layumi/DGNet/blob/master/reIDfolder.py

**Comment by jerry-chenrb** [comment]
Thank you very much for your reply. I really want to use MASK and other manual annotation information, such as color, but these information is edited in the Jason file, so I need to load Jason.
 I can't open the website you provided. I found it on your homepage. It should be this https://github.com/NVlabs/DG-Net/blob/master/reIDfolder.py.
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Zhedong Zheng"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年9月29日(星期天) 晚上6:29
 收件人:&nbsp;"layumi/Person_reID_baseline_pytorch"<Person_reID_baseline_pytorch@noreply.github.com&gt;;
 抄送:&nbsp;"1317054806"<1317054806@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [layumi/Person_reID_baseline_pytorch] how to use json (#169)

 

 
Hi @jerry-chenrb
So...you want to read the jason file and load the mask. Right?
I suggest that you may consider to re-write the ImageFolder. For example, you may refer to https://github.com/layumi/DGNet/blob/master/reIDfolder.py

**Comment by layumi** [comment]
Sorry. I just sent a link of my private repo to you.  Yes, it is. You may consider to add some function to load json file.
