### ISSUE TITLE
关于norm feature

### ISSUE THREAD

**Issue by cosimo17** [layumi/Person_reID_baseline_pytorch#175]
在test.py里的extract_feature函数里。我发现网络输出的feature还需要除以一个范数，然后再和范数拼接在一起。这里不是很理解，为什么要这样？这样一来32张图片就变成了96个512的向量，怎么对应起来？

**Comment by layumi** [comment]
你好。 具体是哪几行呢。
32个inputs还是 32个512的向量。
如果是PCB的话，输出的是32个 512*npart的向量。 npart是切条个数。

**Comment by cosimo17** [comment]
> 你好。 具体是哪几行呢。
> 32个inputs还是 32个512的向量。
> 如果是PCB的话，输出的是32个 512*npart的向量。 npart是切条个数。

test.py 的182行

**Comment by cosimo17** [comment]
sorry，我理解错了，features里是所有图片的特征向量，ff里才是每个batch的32张图片的向量.
另外一个问题是为什么特征向量需要再除以一个范数？

**Comment by layumi** [comment]
简单的说，我们需要用cosine距离。 

分类学出来的特征本质上是夹角相同，但是norm不一样的特征。推荐看large margin softmax 可以帮助理解。

**Comment by cosimo17** [comment]
ok。我去康康。thanks
