### ISSUE TITLE
关于相似度的阈值

### ISSUE THREAD

**Issue by cosimo17** [layumi/Person_reID_baseline_pytorch#176]
reid似乎只需要topk的结果，如果我想通过特征向量间的距离（欧式距离或者余弦相似度）来判断两个人是否是同一个人，阈值设多少合适呢？
我需要在自己的task上，横向对比你的repo和另一个reid的网络，另一个网络的阈值已经设好了，但是我发现你的网络提取的特征向量和另一个网络区别较大（类间差异的相对大小）。想请问下，具体你的model的话，阈值设多少比较合适

**Comment by layumi** [comment]
类似[1]的 Fig.5，你可以在验证/测试集上做一个统计。然后根据统计的结果设置阈值。

[1] Dual-path convolutional image-text embedding with instance loss https://arxiv.org/pdf/1711.05535.pdf

**Comment by cosimo17** [comment]
好的。多谢
