### ISSUE TITLE
Train on multiple object classes? (Cars, pedestrians etc.)

### ISSUE THREAD

**Issue by tiberium24** [layumi/Person_reID_baseline_pytorch#184]
Hello,

Is it possible to train the network simultaneously on different object classes such as cars pedestrians bicycles etc? The goal is to track all of them and distinguish also among different people cars etc.

**Comment by layumi** [comment]
@tiberium24 
Sure. You could train the model on one mixed dataset (person dataset +vehicle dataset). I think it is feasible, but the performance may be limited due to the different low-level pattern between the pedestrians and vehicles.

**Comment by tiberium24** [comment]
That makes sense, thanks a lot!
