### ISSUE TITLE
Validation is a part of training data

### ISSUE THREAD

**Issue by Dipeshtamboli** [layumi/Person_reID_baseline_pytorch#196]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/6cbc2e6de7dbea526b23380c691938a9350a6b71/train.py#L119

Here the only **train** should be used instead of **train_all**.

**Comment by layumi** [comment]
Thank you @Dipeshtamboli 
By default, train_all = ''
https://github.com/layumi/Person_reID_baseline_pytorch/blob/6cbc2e6de7dbea526b23380c691938a9350a6b71/train.py#L114
