### ISSUE TITLE
python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir /Markrt/pytorch

### ISSUE THREAD

**Issue by destinya123** [layumi/Person_reID_baseline_pytorch#198]
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    model = ft_net(len(class_names), opt.droprate, opt.stride)
TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given

Can you tell me how to fix it?

**Comment by wskbest** [comment]
Hello, how did you fix it? I have this question, too.
