### ISSUE TITLE
Error when running test.py

### ISSUE THREAD

**Issue by JuanchoWang** [layumi/Person_reID_baseline_pytorch#20]
Hi, @layumi. Thanks for the great code. I tried your code on Market-1501 and it worked very well. Now I have trained the model for DukeMTMC-reID but when running test.py I got such errors as below

RuntimeError: inconsistent tensor size, expected tensor [751 x 512] and src [702 x 512] to have the same number of elements, but got 384512 and 359424 elements respectively
RuntimeError: While copying the parameter named classifier.0.weight, whose dimensions in the model are torch.Size([751, 512]) and whose dimensions in the checkpoint are torch.Size([702, 512]).

**Comment by layumi** [comment]
Hi @JuanchoWang 
For DukeMTMC-reID, you need to change the Line
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L150

When testing, you do not know the number of training ID.
So you need to manually change it to 702.

**Comment by JuanchoWang** [comment]
@layumi Thanks for your hint. Now it works and the result also looks the same as you mentioned in the introduction. ;)
