### ISSUE TITLE
Loading pretrained model and resetting the classifier

### ISSUE THREAD

**Issue by Dipeshtamboli** [layumi/Person_reID_baseline_pytorch#204]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/6cbc2e6de7dbea526b23380c691938a9350a6b71/train.py#L323
Here, are we training the feature extractor also? Like Resnet convolutional params in this case or we are just training the classifier which we appended in the end?

**Comment by layumi** [comment]
Hi @Dipeshtamboli 
Sorry for the late response. Yes.  
`ignored_params ` is the classifier, which learned from scratch. I want to set one large lrRate. 
`basic_params` is the feature extractor, which is initialized with ImageNet pretrained weights. 
https://github.com/layumi/Person_reID_baseline_pytorch/blob/6cbc2e6de7dbea526b23380c691938a9350a6b71/train.py#L325
