### ISSUE TITLE
In Training process.

### ISSUE THREAD

**Issue by eric82714** [layumi/Person_reID_baseline_pytorch#205]
@layumi Hello, I want to ask when I was training my own data. I found my val acc and val loss always 0.
Can you tell me where is the problem?

**Comment by layumi** [comment]
Hi @eric82714 
First of all, you may check your data preparation. Is the validation folder correct?

**Comment by eric82714** [comment]
@layumi I put my validation data in a folder named val, and in val folder has every person sub-folder. So it is correct, right?
