### ISSUE TITLE
ValueError: Format 'jpg' is not supported

### ISSUE THREAD

**Issue by absagargupta** [layumi/Person_reID_baseline_pytorch#208]
I have done all the installations as instructed. 
When i run the command: python train.py --gpu_ids 1 --name ft_ResNet50 --train_all --batchsize 32

I get the error ValueError: Format 'jpg' is not supported
The full traceback is given below:
Epoch 0/59
----------
/home/sagar18174/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:122: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
train Loss: 3.7450 Acc: 0.2972
val Loss: 1.7339 Acc: 0.5646
Traceback (most recent call last):
  File "train.py", line 385, in <module>
    num_epochs=60)
  File "train.py", line 255, in train_model
    draw_curve(epoch)
  File "train.py", line 289, in draw_curve
    fig.savefig( os.path.join('./model',name,'train.jpg'))
  File "/home/sagar18174/miniconda3/envs/AIhpc2/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/sagar18174/miniconda3/envs/AIhpc2/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2014, in print_figure
    canvas = self._get_output_canvas(format)
  File "/home/sagar18174/miniconda3/envs/AIhpc2/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1956, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
any help will be highly appreciated

**Comment by layumi** [comment]
Hi @absagargupta 
It is widely-know issue due to the PIL version. 
You have two choice, one is to downgrade PIL to 7.0 , the other choice is to save `png`. I suggest to try save `png` first. 
It will be fine. Thanks a lot.
