### ISSUE TITLE
About “ff = ff.div(fnorm)”

### ISSUE THREAD

**Issue by OrchidBrando** [layumi/Person_reID_baseline_pytorch#215]
Hello, I have a place that I don't quite understand. After obtaining the model output, why divide the output by its 2-norm. If not doing so, will it affect the results? Thank you!

**Comment by layumi** [comment]
We use cosine similarity instead of euclidean distance. 
For cosine similarity, we need to normalize the feature.

**Comment by OrchidBrando** [comment]
Thanks for your answer! It really solved my doubts.
