### ISSUE TITLE
关于引用的问题

### ISSUE THREAD

**Issue by finger-monkey** [layumi/Person_reID_baseline_pytorch#216]
您好，我在您提供的基准代码上（不加任何训练技巧）做了实验，想在自己的论文里引用您的这个代码，不知道要如何引用？您的下面代码不知是在哪一片论文里提出来的？
[ResNet-50] | 88.84% | 71.59% | python train.py --train_all

**Comment by layumi** [comment]
感谢。可以引用我这一篇，
The following paper uses and reports the result of the baseline model. You may cite it in your paper.
```bibtex
@article{zheng2019joint,
  title={Joint discriminative and generative learning for person re-identification},
  author={Zheng, Zhedong and Yang, Xiaodong and Yu, Zhiding and Zheng, Liang and Yang, Yi and Kautz, Jan},
  journal={IEEE Conference on Computer Vision and Pattern Recognition (CVPR)},
  year={2019}
}
```

**Comment by finger-monkey** [comment]
抱歉刚才没有说清楚，我指的是下面的这一个：
[ResNet-50] | 88.84% | 71.59% | python train.py --train_all

**Comment by layumi** [comment]
![image](https://user-images.githubusercontent.com/8390471/84559023-c7ec7800-ad7a-11ea-8104-07b39c0df0ba.png)
接近我paper里面table 3 这个？

**Comment by finger-monkey** [comment]
和这个接近，不过精度会再低一点。就是您开源代码里面列表上的
https://github.com/layumi/Person_reID_baseline_pytorch
Trained Model模块下的第一个。

**Comment by layumi** [comment]
我没有report过完全一样的，，或者你可以引用一个我早期的结果
```bibtex
@article{zheng2018discriminatively,
  title={A discriminatively learned CNN embedding for person reidentification},
  author={Zheng, Zhedong and Zheng, Liang and Yang, Yi},
  journal={ACM Transactions on Multimedia Computing, Communications, and Applications (TOMM)},
  volume={14},
  number={1},
  pages={13},
  year={2018},
  publisher={ACM}
}
```

**Comment by finger-monkey** [comment]
好的，十分感谢
