### ISSUE TITLE
同一个摄像头下的人员无法重识别

### ISSUE THREAD

**Issue by LoryMANG** [layumi/Person_reID_baseline_pytorch#217]
我尝试用基于Market1501训练的模型测试自己的图片，然后准备了一批图片，其中有三个人
运行test.py保存特征值，运行demo.py保存结果图片
有一个现象是：当要查询的图片是camera1拍摄人物1，结果中显示不是camera1的人物1都找到了，但是camera1拍到的人物1就匹配不上
所以查询人物是否仅支持非同一个摄像头拍到的图片？

**Comment by layumi** [comment]
是支持的。主要是这些图像都太简单了。在reID的定义中，要找不同摄像头的，所以默认是不算“太简单的”同摄像头。
你可以用initial的 ranking list来展示，你会发现同摄像头一般都排在前面。
