### ISSUE TITLE
multiple query testing含义

### ISSUE THREAD

**Issue by HanwenCao** [layumi/Person_reID_baseline_pytorch#219]
请问multiple query testing是什么意思，是re-id领域的专有词吗？谢谢

**Comment by layumi** [comment]
你好 @HanwenCao 

multiple query就是使用多张 同一个摄像头的图像去检索。 你可以看 
https://www.zhihu.com/question/292321651/answer/479913359

**Comment by HanwenCao** [comment]
Thank you!
