### ISSUE TITLE
请问这个random erasing 是针对分类不是检测的吧

### ISSUE THREAD

**Issue by ZeKunZhang1998** [layumi/Person_reID_baseline_pytorch#228]

**Comment by layumi** [comment]
Random erasing is one kind of data augmentation methods. Actually, it could be applied to various tasks, including image retrieval, semantic segmentation and classification. You may check the original paper.

**Comment by ZeKunZhang1998** [comment]
Thanks .



---原始邮件---
发件人: "Zhedong Zheng"<notifications@github.com&gt;
发送时间: 2020年9月3日(周四) 下午2:37
收件人: "layumi/Person_reID_baseline_pytorch"<Person_reID_baseline_pytorch@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ZhangZekun"<836963662@qq.com&gt;;
主题: Re: [layumi/Person_reID_baseline_pytorch] 请问这个random erasing 是针对分类不是检测的吧 (#228)




 
Random erasing is one kind of data augmentation methods. Actually, it could be applied to various tasks, including image retrieval, semantic segmentation and classification. You may check the original paper.
