### ISSUE TITLE
understanding data directory

### ISSUE THREAD

**Issue by UsamaI000** [layumi/Person_reID_baseline_pytorch#235]
Hi,
Hope you are doing well. I am writing you this mail regarding the github repo of person reID baseline https://github.com/layumi/Person_reID_baseline_pytorch.I am new to reID. Kindly, tell me how you use dataset which is prepared in pytorch folder using prepare.py. The folder structure is.
├── Market/│ 
├── bounding_box_test/      Files for testing (candidate images pool)│ 
├── bounding_box_train/    Files for training │
├── gt_bbox/                       Files for multiple query testing │ 
├── gt_query/                      We do not use it│ 
├── query/                           Files for testing (query images)│ 
├── readme.txt│ 
                          ├── pytorch/│ 
                               ├── train/ /* train │ 
                                    ├── 0002| 
                                    ├── 0007| ...│ 
                          ├── val/              val│ 
                          ├── train_all/      train+val  
                          ├── query/         query files  
                          ├── gallery/        gallery files 
In pytorch folder when i open train_all/ it has folders corresponding to training id of person like 0002, 0007, 0010 etc but not all identities 0001, 0003 etc these are present in query/ folder. According to my understanding we use train/ folder in training but it doesn't has all identities. Shouldn't we have all identities to train model on because if model hasn't seen those identities previously in training how will it perform good on test?
Kindly, help me clearing this. Thankyou

**Comment by layumi** [comment]
Hi @UsamaI000 
Person re-id is one sub-task of image retrieval rather than image recognition (classification) 
The training set and testing set do not share overlap categories (identities). 
When testing, we use the model to extract visual feature for matching and ranking.

**Comment by UsamaI000** [comment]
Thanks, got it
