### ISSUE TITLE
Pre-processing before training

### ISSUE THREAD

**Issue by JuanchoWang** [layumi/Person_reID_baseline_pytorch#24]
Hi @layumi, I found you normalize the image pixel with fixed mean value and standard  deviation for each channel respectively. I wonder how to determine these three pairs of values. Are they only suitable for Market-1501?

Thanks a lot! ;)

**Comment by layumi** [comment]
Hi @JuanchoWang ,
I use the mean value from ImageNet. 
Actually, I have tried the mean value of market-1501. There is no siginificant difference with the final result.

**Comment by JuanchoWang** [comment]
Alright, I understand now. I didn't know it is routine practice to normalize with these values from ImageNet. Thank you very much, @layumi !
