### ISSUE TITLE
ft_net vs ft_net_dense

### ISSUE THREAD

**Issue by k-vineeth** [layumi/Person_reID_baseline_pytorch#247]
I am getting high inference time on ft_net_dense(0.2 sec) compared to ft_net(0.1 sec).
The ft_net is a resnet50 model with size 106mb
The ft_net_dense is a densenet model with size 36mb.
I was expecting vice versa. Can someone explain ?
-Thanks in advance

**Comment by chetansarmak** [comment]
Yeah , I have seen the same 
Any reason @layumi  ?

**Comment by layumi** [comment]
It is due to Flops. DenseNet contains more add and multiplication operations than ResNet.
