### ISSUE TITLE
Is bottleneck better than conv 1*1?

### ISSUE THREAD

**Issue by lingfengyueguang** [layumi/Person_reID_baseline_pytorch#26]
I find you use bottleneck instead of conv 1*1 and classfier .What effect will  this operation have?

**Comment by layumi** [comment]
1. Conv 1\*1 has the same effect with fully-connect layer(Linear layer).
2. Why add bottleneck? It is highly based on empirical result.
In our implement, we find that adding one bottleneck (512 fully connect layer) is help to learn better pedestrian descriptor. 
In my opinion, the fc layer forces the network to learn the dense representation.
