### ISSUE TITLE
after test.py tee is 'tee' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Uchirgerel** [layumi/Person_reID_baseline_pytorch#260]
I'm currenly running on windows 10 64bit

After preparing database I wrote path to dataset path\\pytorch (prepared one)  and then executed train.py but at first it had a problem about freeze smthng apparently i fixed the issue by changing num_workers = 0 

And then I did executed test.py and I got this error 

C:\Users\Uchka\.conda\envs\py37\lib\site-packages\torchvision\transforms\transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
-------test-----------
32
64
96
128
160
192
224
256
288
320
352
384
416
448
480
512
544
576
608
640
672
704
723
32
64
96
128
160
192
209
ft_ResNet50
'tee' is not recognized as an internal or external command,
operable program or batch file.

I have another question here

in command line section what should be written at "--name" function My guess is maybe the model name or is it not ?

python test.py --gpu_ids 0 --name ft_ResNet50 --test_dir C:\Users\Uchka\Desktop\Diploma\Market-1501-v15.09.15\pytorch  --batchsize 32 --which_epoch 59

**Comment by Eliza-wxq** [comment]
Has the problem been solved?

**Comment by layumi** [comment]
"--name"  is the model name when you train the model. 
You do not need to provide the whole path.
