### ISSUE TITLE
关于训练和测试时所遇到各种各样的问题(学习率、策略、测试)

### ISSUE THREAD

**Issue by CynicalHeart** [layumi/Person_reID_baseline_pytorch#261]
哲东博士，我又来了。阅读并跑过您`triplet loss`代码后，这次看到您加入`circle loss`，果断clone跑起来，可是效果并没有达到我的预期，在反复训练后，我总结了几个困惑我的问题，希望能够得到您的解答。

### 训练
1. 学习率一直是困扰着我的难事，您在代码中采用`lr=0.05`，为了使得`rank-1`达到90以上，我不停的去做调整，包括0.01，0.02，0.03，0.035，0.05.....，但是要么出现`loss`在初始几个`epoch`迅速下降后趋于平缓，要么先升后降，持续震荡无法收敛。请问您如何根据自己的参数选择合适的学习率。  

2. 我发现您将学习率分为`base`和`classifier`，`base_params`是初始`lr`的0.1，这样做的深层意义是什么，是因为度量相较于分类更难收敛么？  您的`warm up`策略我也不是非常理解，它是动态改变学习率的策略，而代码中在0.1的基础上不断叠加，取上限制为1后直接与`loss`相乘，这样的反向传播相当于在`circle loss`或交叉熵上乘了一个小数，神奇的是它起作用了:flushed:

3.  fp16的出现让我这个老式1070机器仿佛焕然一新，但是伴随它出现的是频繁的梯度爆炸，即使我减小了`batch_size`，后来不得不降低`circle loss`的`γ`，它在原论文中取256为最佳，但是我试了一次，收敛都做不到:laughing:，只能用32或者64比较稳定，我还能做哪些努力才能减少梯度爆炸的频率呢。  

### 测试
`multiple_scale`搭配`interpolate`在做上采样数据增强，测试期间水平翻转的策略我在您其他回答中发现了（也是在增强），但是到了代码这里，让我有点迷糊。  

```python
            if (i == 1):
                img = fliplr(img) 
               ......
            outputs = model(input_img)
            ff += outputs
```
`ff`是局部变量，它记录一个批次的向量值，但是翻转后提取的特征和没翻转提取的特征直接加起来（单步调试ff依旧是[n,512]）,为什么能够代表成是这个批次的平均值呢，我再`MOT`中计算短轨迹特征平均值时，是把一个人的N个特征按列求平均压缩成[1,512]作平均值，这种方法可以应用到`multi-query`吗。

> 问题的确太多了，如果您有时间的话可以省略的看下，希望能够得到您的解答！这个领域能够求教的人好少呀:cry:

**Comment by layumi** [comment]
我这边 circle loss 也使用了一下 目前发现 batchsize  32的时候结果好一些。同时lrRate也可以大一些。和原来的cross entropy loss 一起用。 circle loss 的gamma 推荐用 64 或者 32.

**Comment by CynicalHeart** [comment]
> 我这边 circle loss 也使用了一下 目前发现 batchsize 32的时候结果好一些。同时lrRate也可以大一些。和原来的cross entropy loss 一起用。 circle loss 的gamma 推荐用 64 或者 32.

`circle loss`作者的论文中表述`γ`越大约贴近难采样`triplet loss`，我经过实验的多次比对`γ=256、128`模型性能反而下降了。您工作中，学习率分为`base`和`classifier`，`base_params`是初始`lr`的0.1，所以学习率初始就小，这样做的好处是什么呢，经历了两个月学习我依旧没搞明白。现在训练`rank-1`只到92.4，我再加ibn或者Se试试吧

**Comment by layumi** [comment]
@CynicalHeart 
嗯嗯 ，感谢
0.1 是希望保留原来的pretrained模型的weight。
