### ISSUE TITLE
Type of the machine learning on the repo

### ISSUE THREAD

**Issue by aktaseren** [layumi/Person_reID_baseline_pytorch#271]
Hi @layumi thank you for making available this repo. I have only a low-level question to be sure of the approach used on that repo. 

Can I say that Semi-Supervised learning approach was taken on that repo? Can I assume that mostly 'Joint Discriminative and Generative Learning for Person Re-identification' paper was implemented on the repo? 

Thanks,
Eren

**Comment by layumi** [comment]
Hi @aktaseren 

Thanks. We do not involve semi-supervised learning in this repo. 
This repo provides the baseline result as benchmark for 'Joint Discriminative and Generative Learning for Person Re-identification'
 
Thanks

**Comment by aktaseren** [comment]
@layumi thank you for this.
