### ISSUE TITLE
Implementation for Fisheye Camera Images

### ISSUE THREAD

**Issue by aktaseren** [layumi/Person_reID_baseline_pytorch#273]
Thank you for making available this repo. @layumi @zhunzhong07 @syfafterzy @dyh127 @zhangchuangnankai 

I ran the demo over ResNet for Market1501 as you suggested. I got great accuracy based on that dataset. As I aim to run the repo for my own fisheye camera images, I am having low mAP scores owing to the work principles of fisheye cameras. 

Since the research is limited to fisheye images, I couldn't find a proper powerful pre-trained algorithm based on an unsupervised approach or unsupervised domain adaptation. Do you have any suggestion of the usage of your repo for my fisheye images taken by over-headed fisheye cameras?

I would be grateful if you can guide me on this.

**Comment by layumi** [comment]
Hi @aktaseren 
You may check https://medium.com/@kennethjiang/calibrate-fisheye-lens-using-opencv-333b05afa0b0

**Comment by aktaseren** [comment]
@layumi thank you very much for the suggestion. I will try this.
