### ISSUE TITLE
损失函数问题

### ISSUE THREAD

**Issue by LQ199302** [layumi/Person_reID_baseline_pytorch#28]
请问这个代码计算损失函数时，是同时考虑了分类损失和验证损失吗？

**Comment by layumi** [comment]
Hi @LQ199302 ,
Thanks for your interest.
I haven't included the verification loss into this repo.
This code only used the classification loss.

You may refer to my TOMM code. https://github.com/layumi/2016_person_re-ID

**Comment by LQ199302** [comment]
Thanks a lot! @layumi
