### ISSUE TITLE
请问有ResNet-50+DG实验数据吗？

### ISSUE THREAD

**Issue by finger-monkey** [layumi/Person_reID_baseline_pytorch#298]
您好，请问有ResNet-50+DG实验数据吗？以便于更好地做对比。

**Comment by layumi** [comment]
预训练模型么？因为上传比较麻烦就没有存。您可以跑一个，基本在2小时以内就可以训练好了。
DG数据的话可以从百度网盘或者google drive下载到。

**Comment by finger-monkey** [comment]
好的，谢谢。
