### ISSUE TITLE
I followed all your instruction on train, test and evalutate, but only reached rank@1=~0.75, mAP=~.6 on market

### ISSUE THREAD

**Issue by ElijhaLee** [layumi/Person_reID_baseline_pytorch#3]
Thanks for share this wonderful code! I download your code, only changed the data dir, and followed all your instruction and hyperparameters; also the same version of pytorch and torchvision, but I tried several times, only reached rank@1=~0.75 and mAP=~0.6... What would you think the reason is? Thx again, good luck with your work!

**Comment by layumi** [comment]
Hi @ElijhaLee ,
Do you change the batch size?
I add some code to generate training curves.Would you like to show me you training curves? It may help to find the bug.

**Comment by layumi** [comment]
Do you use python2.7? It may contain some difference.

**Comment by ElijhaLee** [comment]
Hi, @layumi ,
thanks for your reply! I used python 3.6, maybe that explain the gap between your and my result. I just notice your code update, and I will re-train my model; if there is still a big gap, I will show the training curve to you!

**Comment by ElijhaLee** [comment]
My batch size is 32, which is consistent with your instruction in readme. Should I change it to 16?

**Comment by layumi** [comment]
Hi @ElijhaLee
Just use python3.6 and batchsize 32. I think it is fine.

**Comment by ElijhaLee** [comment]
Hi @layumi ,
I trained again, but the result is still not good. rank@1=0.8, map=0.62. I used all train-all option and batchsize=32, here is my curve:
![train](https://user-images.githubusercontent.com/12457147/34776959-9c68447e-f653-11e7-8431-7a21af6ca655.jpg).

For what reason can you guess that lead to this gap?

**Comment by layumi** [comment]
Hi @ElijhaLee 
I think the training curves are OK. I could not figure out what is wrong.
You may try to update the pip or conda. I recommend to use anaconda.
If you use pip, you may try
```
pip install --upgrade pip
pip install numpy
pip install other_package
```
If you use conda, you may try 
```
conda config --add channels conda-forge
conda update
conda install numpy
conda install other_package
```
Alternatively,  would you like to test the code on another machine?

**Comment by ElijhaLee** [comment]
Thanks for your detailed instruction, and I will try it! 
Good luck with your work!

**Comment by BrettLL** [comment]
@layumi I use python2.7 and modify transform.resize ,super._init_(),  I can train a model. Train_acc can reach almost 1.0, but val_acc only 0.20+. The eval result is also not good, I want to know any other differences between 2.7 and 3.6??

**Comment by layumi** [comment]
Hi @BrettLL 
How you modify the transform.resize? 
In some cases, some default setting may be very different.
For example, the default setting of `RandomResizedCrop` is for ImageNet.
`class torchvision.transforms.RandomResizedCrop(size, scale=(0.08, 1.0), ratio=(0.75, 1.3333333333333333), interpolation=2)` 
It will randomly resize the image from 0.08 to 1.0

If possible, using python3.6 with anaconda is a better choice.

**Comment by layumi** [comment]
@BrettLL 
Would you like to post your code and pytorch/torchvision version here?
They may do help to diagnose your bug.

**Comment by layumi** [comment]
@BrettLL Do you install torchvision from source? Try it.
```
git clone https://github.com/pytorch/vision
cd vision
python setup.py install
```

**Comment by BrettLL** [comment]
@layumi I only modify transforms.resize to transforms.Scale(). My pytorch and torchvision  version is 0.2.0 and 0.1.9. Val top1 error dosen't decrease when it comes to 0.6.

**Comment by layumi** [comment]
Hi @BrettLL 
If possible, please update your `torchvision` and `pytorch`.

**Comment by BrettLL** [comment]
@layumi ok, I will try. Thanks~
