### ISSUE TITLE
About DukeMTMC-reID Dataset performance

### ISSUE THREAD

**Issue by zqigolden** [layumi/Person_reID_baseline_pytorch#30]
Hello, 
I want to test the code on DukeMTMC-reID dataset and need to improve the performance. In the README.md, it said: 
> Futhermore, you also can test our code on DukeMTMC-reID Dataset. Our baseline code is not such high on DukeMTMC-reID Rank@1=64.23%, mAP=43.92%. Hyperparameters are need to be tuned.

Which hyperparameters should I adjust? Any informations is helpful.
Thank you and waiting for your reply.

**Comment by layumi** [comment]
@zqigolden 
I think you may try changing the learningRate and batchsize first.
Then you may try using larger input size.
