### ISSUE TITLE
无法复现作者提供的精度

### ISSUE THREAD

**Issue by XGBoost** [layumi/Person_reID_baseline_pytorch#307]
rt
在使用circle loss和triplet loss训练网络的时候，使用的命令为作者提供的命令
验证了一下，发现得到的精度分别为
![image](https://user-images.githubusercontent.com/23393128/146877912-f9ced6c3-f76f-4da2-bd9d-f25ff3767ffd.png)

不知道问题出在哪里，没有使用reranking这种，想问下作者在给这个精度的时候，使用了reranking的操作了吗？谢谢

**Comment by layumi** [comment]
Hi @XGBoost 
Thanks a lot for reporting the result. 
I do not use re-ranking. But sometime the performance could be different due to the machine and data shuffle.

**Comment by XGBoost** [comment]
Thank you for your reply.
