### ISSUE TITLE
Use a video as gallary

### ISSUE THREAD

**Issue by notsong** [layumi/Person_reID_baseline_pytorch#313]
Hello, if I use a video instead of Gallery, do I need to use the assistance of detection algorithm, such as YOLO, to detect people first and then take crop-image as the comparison object?

**Comment by layumi** [comment]
Hi @notsong  

Sorry for the late response. 
Yes. You may try use MaskRCNN to detect person and then save the cropped images.

**Comment by GayatriPurandharT** [comment]
Hi, I'm curious about a real-time comparison of each detected person with all the feature representations of query images. Please share your view on real-time implementation. Thanks!

**Comment by notsong** [comment]
I think you might be able to convert the images in the library to feature vectors and store them, and then compare them directly with feature vectors next time.

> Hi, I'm curious about a real-time comparison of each detected person with all the feature representations of query images. Please share your view on real-time implementation. Thanks!

[GayatriPurandharT](https://github.com/GayatriPurandharT)

**Comment by notsong** [comment]
> Hi, I'm curious about a real-time comparison of each detected person with all the feature representations of query images. Please share your view on real-time implementation. Thanks!

I think you might be able to convert the images in the library to feature vectors and store them, and then compare them directly with feature vectors next time.
