### ISSUE TITLE
Input transformation

### ISSUE THREAD

**Issue by Simon4Yan** [layumi/Person_reID_baseline_pytorch#32]
Hello ZZD!

I change this line https://github.com/layumi/Person_reID_baseline_pytorch/blob/2ead235e58b99f42b1e5b944a89617ada10c034a/train.py#L61 to transforms.Resize((288, 144), interpolation=3). And I get 76.5% in rank-1 and 58.9% in mAP on Duke dataset.

**Comment by layumi** [comment]
Hi, @Simon4Yan 
Thank you. Since the size ratio of  images in DukeMTMC-reID are not  1:2 (like Market-1501), it might be good to fix it to 1:2. You are right. 
Thank you again for reporting it.

**Comment by EricWu123** [comment]
why I cannot get the 76.5% in rank-1 and 58.9% in mAP on Duke dataset, just 46.2% in rank-1 and 42.6% in mAP on Duke dataset. I want to know whether you change other hyperparameters?
