### ISSUE TITLE
Single camera dataset has test results with all Ranks at 1.0 with mAp changing

### ISSUE THREAD

**Issue by nikky4D** [layumi/Person_reID_baseline_pytorch#325]
I'm using my custom dataset that has been prepared using same format in the tutorial. I don't have multiple cameras so in``` evaluate.py```, in  the ```evaluate function```, I set the ```camera_index = []```

But I find that with the teacher training, my test results all show Rank at 100% for all Rank levels.
If I do not add the ```camera_index = []```, then results are all 0s for Rank and mAp

Any advice on if I am doing this correctly for a single camera view?

**Comment by layumi** [comment]
Hi @nikky4D 
One simple solution is to set different camera ID by  ``range(N)''

**Comment by nikky4D** [comment]
Thank you.
