### ISSUE TITLE
GPU reranking got worse evaluation performance (mAP and rank-k)

### ISSUE THREAD

**Issue by SuperbTUM** [layumi/Person_reID_baseline_pytorch#327]
**Describe the bug**
Hi Zhedong, what a fascinating work you have done! But correct me if I am wrong, I found something strange in the GPU reranking part. I assume It is expected to accelerate the reranking process with CUDA and achieve minor improvement in the evaluation at the same time. But when I test it with my customized dataset, I found the GPU version (GNN based) gave worse results, compared with the regular reranking process. Not sure if the method is only suitable for certain backbones/reid datasets.

**To Reproduce**
I followed the code logic and the followings are two versions of reranking call.
Ordinary call  --
```
distmat, query_features, gallery_features = pairwise_distance(features, query, gallery)
print('Applying person re-ranking ...')
distmat_qq, _, _ = pairwise_distance(features, query, query)
distmat_gg, _, _ = pairwise_distance(features, gallery, gallery)
distmat = re_ranking(distmat.numpy(), distmat_qq.numpy(), distmat_gg.numpy())
return evaluate_all(distmat, query=query, gallery=gallery, cmc_flag=cmc_flag)
```
GPU reranking call  --
```
indices = gnn_reranking(query_features, gallery_features)
query_labels = np.asarray(query)[:, 1]
query_camids = np.asarray(query)[:, 2]
gallery_labels = np.asarray(gallery)[:, 1]
gallery_camids = np.asarray(gallery)[:, 2]
return evaluate_ranking_list(indices, query_labels, query_camids, gallery_labels, gallery_camids)
```

**Expected behavior**
GPU reranking returns better results.

**Screenshots**
Unavailable

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox
 - Version Python 3.7; Pytorch 1.7.0

**Additional context**
There is a significant deduction when GPU reranking is applied. (~15%)

**Comment by layumi** [comment]
Hi @SuperbTUM  

Do you set the k1 and k2? You may change the k value to tune it.

**Comment by SuperbTUM** [comment]
@layumi Thanks for the response. I used identical k1 (=20) and k2 (=6) in the two implementations. Do you suggest I use different k1 and k2 settings in the GPU (GNN) version?

**Comment by layumi** [comment]
Hi @SuperbTUM  
Is the result close or not?  How about the baseline performance before reranking?
Could you give me more information? Thanks a lot.

**Comment by SuperbTUM** [comment]
@layumi I am using my customized reid dataset to test the model (resnet50-ibn). The problem is the results are not close at all... I can't share my code right now as it belongs to my laboratory... Anyway, there is a relative 10%-15% (huge) deduction (both on person and vehicle reid) using the same feature representations but different reranking strategies (given the sample code above). I am wondering if this is possible or maybe I made a mistake on how to call the functions properly.

**Comment by SuperbTUM** [comment]
@layumi Hi Zhedong, I am sorry. I think I messed up with the baseline... There is no deduction now. Thank you...
