### ISSUE TITLE
adding requirement.txt

### ISSUE THREAD

**Issue by BarRozenman** [layumi/Person_reID_baseline_pytorch#328]
I'm having a hard time setting up a proper environment for the repository since there are many packages involved and I haven't found a detailed description of the requirement.

Is there a possibility of adding a requirement.txt file?
of course, a docker file or conda environment will also be great

Thanks

**Comment by layumi** [comment]
Thanks a lot @BarRozenman 
I will add it soon.

**Comment by layumi** [comment]
You may check https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/requirements.txt

**Comment by layumi** [comment]
I do not include pytorch and torch vision, because they are based on your system.
