### ISSUE TITLE
Is this project available for windows?

### ISSUE THREAD

**Issue by scut-salmon** [layumi/Person_reID_baseline_pytorch#34]

**Comment by layumi** [comment]
No. I haven't modified it for windows.

But you may have a try. Note that  you may need to change the file path style such as 'D://'.

**Comment by Wuranker** [comment]
No problem, but need to make some changes:
1. num_workers=8 ==>
    num_workers=0
2. os.mkdir(dir_name) ==>
    os.makedirs(dir_name, exist_ok=True)
3. fig.savefig( os.path.join('./model',name,'train.jpg')) ==>
    fig.savefig( os.path.join('./model',name,'train.png'))
4. file path style like as r"D:\" or "D://"
Good luck!
