### ISSUE TITLE
use timms model for training

### ISSUE THREAD

**Issue by nikky4D** [layumi/Person_reID_baseline_pytorch#348]
Is it possible to use a model from huggingface or timms to train? Is there an example I can follow for this?

**Comment by layumi** [comment]
Yes. @nikky4D  
You may refer to https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/model.py#L110 

Please note that different model you may need to change the final fc input dimension.

**Comment by nikky4D** [comment]
Thank you.
