### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by scut-salmon** [layumi/Person_reID_baseline_pytorch#35]
I was using trained model to extract feature by command
python test.py --gpu_ids 1 --name ft_ResNet50 --test_dir Market-1501-v15.09.15/pytorch/  --which_epoch 59
However, there exists the following error:
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCStorage.cu:58

How can I solve the problem? Any suggestion would be appreciable.

Thanks,
Zhang

**Comment by zgplvyou** [comment]
change the batchsize

**Comment by scut-salmon** [comment]
@zgplvyou Thanks, work for me.
