### ISSUE TITLE
Runtimeerror when running train.py

### ISSUE THREAD

**Issue by wildanshf** [layumi/Person_reID_baseline_pytorch#350]
Iam using google colab and this error appear when i run train.py

![image](https://user-images.githubusercontent.com/63804246/219329517-354bb6c5-d49b-42e2-a66e-12b9de2ad453.png)

**Comment by layumi** [comment]
Hi @wildanshf 

It seems an error about pin memory. 
Could you try to set pin_memory = False to see whether it can work?

**Comment by wildanshf** [comment]
its worked, thank you
