### ISSUE TITLE
Acc: 0.0000/1.0000 when training for each epoch

### ISSUE THREAD

**Issue by scut-salmon** [layumi/Person_reID_baseline_pytorch#36]
I just download the Market1501 dataset and run the following command
python prepare.py
python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir Market-1501-v15.09.15/pytorch/

It runs without error and the loss is decreasing with each epoch, however, the acc is abnormal with 0 or 1, just as follow
![train1](https://user-images.githubusercontent.com/20534039/40339173-c0d7b3d4-5dab-11e8-9ba1-e08268153bc4.jpg)
Is there something wrong?
Thanks
Zhang

**Comment by layumi** [comment]
Could you show me your debug log?

**Comment by scut-salmon** [comment]
@layumi Hi, the debug log is as follows,thanks!
23:07:29anaconda3/lib/python3.6/site-packages/torchvision/models/densenet.py:212: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
23:07:29  nn.init.kaiming_normal(m.weight.data)
23:07:29~/Person_reID_baseline_pytorch/model.py:14: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
23:07:29  init.kaiming_normal(m.weight.data, a=0, mode='fan_out')
23:07:29~/Person_reID_baseline_pytorch/model.py:15: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
23:07:29  init.constant(m.bias.data, 0.0)
23:07:29~/Person_reID_baseline_pytorch/model.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
23:07:29  init.normal(m.weight.data, 1.0, 0.02)
23:07:29~/Person_reID_baseline_pytorch/model.py:18: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
23:07:29  init.constant(m.bias.data, 0.0)
23:07:29~/Person_reID_baseline_pytorch/model.py:23: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
23:07:29  init.normal(m.weight.data, std=0.001)
23:07:29~/Person_reID_baseline_pytorch/model.py:24: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
23:07:29  init.constant(m.bias.data, 0.0)
23:07:31net output size:
23:07:31torch.Size([8, 751])
23:07:37[Resize(size=(288, 144), interpolation=PIL.Image.BICUBIC), RandomCrop(size=(256, 128), padding=0), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
23:07:38Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/zhangzhenchang/.torch/models/resnet50-19c8e357.pth
23:07:44100.0%
23:07:44ft_net(
23:07:44  (model): ResNet(
23:07:44    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
23:07:44    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44    (relu): ReLU(inplace)
23:07:44    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
23:07:44    (layer1): Sequential(
23:07:44      (0): Bottleneck(
23:07:44        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44        (downsample): Sequential(
23:07:44          (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        )
23:07:44      )
23:07:44      (1): Bottleneck(
23:07:44        (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (2): Bottleneck(
23:07:44        (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44    )
23:07:44    (layer2): Sequential(
23:07:44      (0): Bottleneck(
23:07:44        (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44        (downsample): Sequential(
23:07:44          (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
23:07:44          (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        )
23:07:44      )
23:07:44      (1): Bottleneck(
23:07:44        (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (2): Bottleneck(
23:07:44        (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (3): Bottleneck(
23:07:44        (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44    )
23:07:44    (layer3): Sequential(
23:07:44      (0): Bottleneck(
23:07:44        (conv1): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44        (downsample): Sequential(
23:07:44          (0): Conv2d(512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False)
23:07:44          (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        )
23:07:44      )
23:07:44      (1): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (2): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (3): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (4): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (5): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44    )
23:07:44    (layer4): Sequential(
23:07:44      (0): Bottleneck(
23:07:44        (conv1): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44        (downsample): Sequential(
23:07:44          (0): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False)
23:07:44          (1): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        )
23:07:44      )
23:07:44      (1): Bottleneck(
23:07:44        (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44      (2): Bottleneck(
23:07:44        (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
23:07:44        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
23:07:44        (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44        (relu): ReLU(inplace)
23:07:44      )
23:07:44    )
23:07:44    (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
23:07:44    (fc): Linear(in_features=2048, out_features=1000, bias=True)
23:07:44  )
23:07:44  (classifier): ClassBlock(
23:07:44    (add_block): Sequential(
23:07:44      (0): Linear(in_features=2048, out_features=512, bias=True)
23:07:44      (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
23:07:44      (2): LeakyReLU(negative_slope=0.1)
23:07:44      (3): Dropout(p=0.5)
23:07:44    )
23:07:44    (classifier): Sequential(
23:07:44      (0): Linear(in_features=512, out_features=751, bias=True)
23:07:44    )
23:07:44  )
23:07:44)
23:07:48Epoch 0/59
23:07:48----------
23:07:49train.py:200: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
23:07:49  running_loss += loss.data[0]
23:12:46train Loss: 0.1478 Acc: 0.0000
23:12:51val Loss: 0.1087 Acc: 0.0000
23:12:52
23:12:52Epoch 1/59
23:12:52----------
23:17:50train Loss: 0.0780 Acc: 0.0000
23:17:56val Loss: 0.0615 Acc: 0.0000
23:17:56
23:17:56Epoch 2/59
23:17:56----------
23:22:54train Loss: 0.0543 Acc: 0.0000
23:23:00val Loss: 0.0441 Acc: 0.0000
23:23:00
23:23:00Epoch 3/59
23:23:00----------
23:27:58train Loss: 0.0417 Acc: 0.0000
23:28:04val Loss: 0.0339 Acc: 0.0000
23:28:04
23:28:04Epoch 4/59
23:28:04----------
23:33:02train Loss: 0.0347 Acc: 0.0000
23:33:08val Loss: 0.0366 Acc: 0.0000
23:33:08
23:33:08Epoch 5/59
23:33:08----------
23:38:06train Loss: 0.0297 Acc: 0.0000
23:38:12val Loss: 0.0455 Acc: 0.0000
23:38:12
23:38:12Epoch 6/59
23:38:12----------
23:43:10train Loss: 0.0263 Acc: 0.0000
23:43:16val Loss: 0.0171 Acc: 0.0000
23:43:16
23:43:16Epoch 7/59
23:43:16----------
23:48:14train Loss: 0.0241 Acc: 0.0000
23:48:20val Loss: 0.0250 Acc: 0.0000
23:48:20
23:48:20Epoch 8/59
23:48:20----------
23:53:18train Loss: 0.0223 Acc: 0.0000
23:53:24val Loss: 0.0240 Acc: 0.0000
23:53:24
23:53:24Epoch 9/59
23:53:24----------
23:58:22train Loss: 0.0206 Acc: 0.0000
23:58:28val Loss: 0.0155 Acc: 0.0000
23:58:28
23:58:28Epoch 10/59
23:58:28----------
00:03:26train Loss: 0.0194 Acc: 0.0000
00:03:32val Loss: 0.0143 Acc: 0.0000
00:03:32
00:03:32Epoch 11/59
00:03:32----------
00:08:30train Loss: 0.0189 Acc: 0.0000
00:08:36val Loss: 0.0163 Acc: 0.0000
00:08:36
00:08:36Epoch 12/59
00:08:36----------
00:13:34train Loss: 0.0168 Acc: 0.0000
00:13:40val Loss: 0.0141 Acc: 0.0000
00:13:40
00:13:40Epoch 13/59
00:13:40----------
00:18:38train Loss: 0.0159 Acc: 0.0000
00:18:44val Loss: 0.0140 Acc: 0.0000
00:18:44
00:18:44Epoch 14/59
00:18:44----------
00:23:42train Loss: 0.0146 Acc: 0.0000
00:23:48val Loss: 0.0104 Acc: 0.0000
00:23:48
00:23:48Epoch 15/59
00:23:48----------
00:28:46train Loss: 0.0144 Acc: 0.0000
00:28:52val Loss: 0.0109 Acc: 0.0000
00:28:52
00:28:52Epoch 16/59
00:28:52----------
00:33:50train Loss: 0.0142 Acc: 0.0000
00:33:56val Loss: 0.0078 Acc: 0.0000
00:33:56
00:33:56Epoch 17/59
00:33:56----------
00:38:54train Loss: 0.0141 Acc: 0.0000
00:39:00val Loss: 0.0141 Acc: 0.0000
00:39:00
00:39:00Epoch 18/59
00:39:00----------
00:43:58train Loss: 0.0138 Acc: 0.0000
00:44:04val Loss: 0.0100 Acc: 0.0000
00:44:04
00:44:04Epoch 19/59
00:44:04----------
00:49:02train Loss: 0.0126 Acc: 0.0000
00:49:08val Loss: 0.0096 Acc: 0.0000
00:49:09
00:49:09Epoch 20/59
00:49:09----------
00:54:07train Loss: 0.0121 Acc: 0.0000
00:54:12val Loss: 0.0084 Acc: 0.0000
00:54:13
00:54:13Epoch 21/59
00:54:13----------
00:59:11train Loss: 0.0111 Acc: 0.0000
00:59:17val Loss: 0.0083 Acc: 0.0000
00:59:17
00:59:17Epoch 22/59
00:59:17----------
01:04:15train Loss: 0.0119 Acc: 0.0000
01:04:21val Loss: 0.0072 Acc: 0.0000
01:04:21
01:04:21Epoch 23/59
01:04:21----------
01:09:19train Loss: 0.0121 Acc: 0.0000
01:09:25val Loss: 0.0079 Acc: 0.0000
01:09:25
01:09:25Epoch 24/59
01:09:25----------
01:14:23train Loss: 0.0107 Acc: 0.0000
01:14:29val Loss: 0.0072 Acc: 0.0000
01:14:29
01:14:29Epoch 25/59
01:14:29----------
01:19:27train Loss: 0.0114 Acc: 0.0000
01:19:33val Loss: 0.0065 Acc: 0.0000
01:19:33
01:19:33Epoch 26/59
01:19:33----------
01:24:32train Loss: 0.0110 Acc: 0.0000
01:24:37val Loss: 0.0083 Acc: 0.0000
01:24:38
01:24:38Epoch 27/59
01:24:38----------
01:29:36train Loss: 0.0108 Acc: 0.0000
01:29:42val Loss: 0.0086 Acc: 0.0000
01:29:42
01:29:42Epoch 28/59
01:29:42----------
01:34:40train Loss: 0.0094 Acc: 0.0000
01:34:46val Loss: 0.0083 Acc: 0.0000
01:34:46
01:34:46Epoch 29/59
01:34:46----------
01:39:44train Loss: 0.0107 Acc: 0.0000
01:39:50val Loss: 0.0084 Acc: 0.0000
01:39:50
01:39:50Epoch 30/59
01:39:50----------
01:44:48train Loss: 0.0104 Acc: 0.0000
01:44:54val Loss: 0.0084 Acc: 0.0000
01:44:54
01:44:54Epoch 31/59
01:44:54----------
01:49:53train Loss: 0.0096 Acc: 0.0000
01:49:59val Loss: 0.0072 Acc: 0.0000
01:49:59
01:49:59Epoch 32/59
01:49:59----------
01:54:57train Loss: 0.0104 Acc: 0.0000
01:55:03val Loss: 0.0105 Acc: 0.0000
01:55:03
01:55:03Epoch 33/59
01:55:03----------
02:00:01train Loss: 0.0104 Acc: 0.0000
02:00:07val Loss: 0.0087 Acc: 0.0000
02:00:07
02:00:07Epoch 34/59
02:00:07----------
02:05:05train Loss: 0.0097 Acc: 0.0000
02:05:11val Loss: 0.0082 Acc: 0.0000
02:05:11
02:05:11Epoch 35/59
02:05:11----------
02:10:10train Loss: 0.0102 Acc: 0.0000
02:10:16val Loss: 0.0118 Acc: 0.0000
02:10:16
02:10:16Epoch 36/59
02:10:16----------
02:15:14train Loss: 0.0100 Acc: 0.0000
02:15:20val Loss: 0.0065 Acc: 0.0000
02:15:20
02:15:20Epoch 37/59
02:15:20----------
02:20:18train Loss: 0.0104 Acc: 0.0000
02:20:24val Loss: 0.0071 Acc: 0.0000
02:20:24
02:20:24Epoch 38/59
02:20:24----------
02:25:22train Loss: 0.0102 Acc: 0.0000
02:25:28val Loss: 0.0069 Acc: 0.0000
02:25:28
02:25:28Epoch 39/59
02:25:28----------
02:30:26train Loss: 0.0083 Acc: 0.0000
02:30:32val Loss: 0.0112 Acc: 0.0000
02:30:32
02:30:32Epoch 40/59
02:30:32----------
02:35:30train Loss: 0.0034 Acc: 0.0000
02:35:36val Loss: 0.0004 Acc: 1.0000
02:35:37
02:35:37Epoch 41/59
02:35:37----------
02:40:35train Loss: 0.0017 Acc: 0.0000
02:40:40val Loss: 0.0003 Acc: 1.0000
02:40:41
02:40:41Epoch 42/59
02:40:41----------
02:45:39train Loss: 0.0013 Acc: 0.0000
02:45:45val Loss: 0.0003 Acc: 1.0000
02:45:45
02:45:45Epoch 43/59
02:45:45----------
02:50:43train Loss: 0.0013 Acc: 0.0000
02:50:49val Loss: 0.0002 Acc: 1.0000
02:50:49
02:50:49Epoch 44/59
02:50:49----------
02:55:47train Loss: 0.0011 Acc: 0.0000
02:55:53val Loss: 0.0002 Acc: 1.0000
02:55:53
02:55:53Epoch 45/59
02:55:53----------
03:00:51train Loss: 0.0010 Acc: 0.0000
03:00:57val Loss: 0.0002 Acc: 1.0000
03:00:57
03:00:57Epoch 46/59
03:00:57----------
03:05:56train Loss: 0.0011 Acc: 0.0000
03:06:01val Loss: 0.0002 Acc: 1.0000
03:06:02
03:06:02Epoch 47/59
03:06:02----------
03:11:00train Loss: 0.0010 Acc: 0.0000
03:11:06val Loss: 0.0002 Acc: 1.0000
03:11:06
03:11:06Epoch 48/59
03:11:06----------
03:16:04train Loss: 0.0011 Acc: 0.0000
03:16:10val Loss: 0.0002 Acc: 1.0000
03:16:10
03:16:10Epoch 49/59
03:16:10----------
03:21:08train Loss: 0.0011 Acc: 0.0000
03:21:14val Loss: 0.0002 Acc: 1.0000
03:21:14
03:21:14Epoch 50/59
03:21:14----------
03:26:12train Loss: 0.0011 Acc: 0.0000
03:26:18val Loss: 0.0002 Acc: 1.0000
03:26:18
03:26:18Epoch 51/59
03:26:18----------
03:31:16train Loss: 0.0011 Acc: 0.0000
03:31:22val Loss: 0.0003 Acc: 1.0000
03:31:22
03:31:22Epoch 52/59
03:31:22----------
03:36:20train Loss: 0.0011 Acc: 0.0000
03:36:26val Loss: 0.0003 Acc: 1.0000
03:36:26
03:36:26Epoch 53/59
03:36:26----------
03:41:25train Loss: 0.0011 Acc: 0.0000
03:41:30val Loss: 0.0003 Acc: 1.0000
03:41:31
03:41:31Epoch 54/59
03:41:31----------
03:46:29train Loss: 0.0011 Acc: 0.0000
03:46:35val Loss: 0.0003 Acc: 1.0000
03:46:35
03:46:35Epoch 55/59
03:46:35----------
03:51:33train Loss: 0.0011 Acc: 0.0000
03:51:39val Loss: 0.0003 Acc: 1.0000
03:51:39
03:51:39Epoch 56/59
03:51:39----------
03:56:37train Loss: 0.0011 Acc: 0.0000
03:56:43val Loss: 0.0003 Acc: 1.0000
03:56:43
03:56:43Epoch 57/59
03:56:43----------
04:01:41train Loss: 0.0011 Acc: 0.0000
04:01:47val Loss: 0.0003 Acc: 1.0000
04:01:47
04:01:47Epoch 58/59
04:01:47----------
04:06:45train Loss: 0.0011 Acc: 0.0000
04:06:51val Loss: 0.0003 Acc: 1.0000
04:06:51
04:06:51Epoch 59/59
04:06:51----------
04:11:50train Loss: 0.0011 Acc: 0.0000
04:11:55val Loss: 0.0003 Acc: 1.0000
04:11:56
04:11:56Training complete in 304m 8s

**Comment by layumi** [comment]
Could you try modifying the line  
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L204
```
epoch_acc = running_corrects * 1.0 / dataset_sizes[phase]
```

**Comment by scut-salmon** [comment]
@layumi It It doesn't seem to work. I change the line to 
`epoch_acc = float(running_corrects) / dataset_sizes[phase]`
and it's ok now.
