### ISSUE TITLE
请问训练途中出现意外终止，如何继续进行训练呢？

### ISSUE THREAD

**Issue by CaptainJi** [layumi/Person_reID_baseline_pytorch#368]
哪个参数可以继续未完的训练呢？

**Comment by layumi** [comment]
你好 目前master branch 没有提供这个功能。因为训练一般就3小时内。  一些 resume 功能可以看develop branch。

**Comment by layumi** [comment]
关于resume 你可以参考 dev branch 这里。 按照关键字搜索resume 把相关代码加入就行。
 https://github.com/layumi/Person_reID_baseline_pytorch/blob/dev/train.py#L62

**Comment by CaptainJi** [comment]
十分感谢解答。已经根据您的提示实现了resume
