### ISSUE TITLE
关于训练tricks说明

### ISSUE THREAD

**Issue by leeburt** [layumi/Person_reID_baseline_pytorch#373]
请教一下，Trained Model的表格中列举了不同模型，不同训练参数下的精度，其中提到的all tricks具体指哪些，我没有找到相关的说明？

**Comment by layumi** [comment]
Hi @leeburt 
就是混合了上面 所有能提升的选项。

**Comment by leeburt** [comment]
谢谢你的回复，我能这么理解吗，以训练[ResNet-50 (all tricks)]为例，python train.py --warm_epoch 5 --stride 1 --erasing_p 0.5 --batchsize 8 --lr 0.02 --name warm5_s1_b8_lr2_p0.5训练中，使用了warm_epoch=5，stride=1，erasing_p=0.5，lr=0.02，batchsize=8这些参数是吗？

**Comment by layumi** [comment]
Hi @leeburt  是的
