### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by robosina** [layumi/Person_reID_baseline_pytorch#376]
I'm curious if person re-identification (ReID) can be used like face recognition tasks. I noticed that we get an output, for example, a vector of size 751 which matches the number of people in the dataset. But, can we use a technique like metric learning here? This would let us use an image of a person as a reference, and then for each new frame, we get an 'embedding vector' for each person. We could then compare these vectors to the reference using cosine similarity.

What I really want to know is, can this person re-identification method in the repository work with people it hasn't seen before if we provide a reference image? In other words, I'm looking for a more general person re-identification method that can handle new people, not just the ones in the original dataset.

**Comment by layumi** [comment]
Yes. But it requires a large and general dataset. 

You may refer to our latest work https://github.com/Shuyu-XJTU/APTM 
It is pre-trained on a large dataset generated by Stable Diffusion.

**Comment by robosina** [comment]
Thanks
