### ISSUE TITLE
作者请问我如何在本项目中使用DG-market数据集进行训练和测试

### ISSUE THREAD

**Issue by qiaosuobutouche** [layumi/Person_reID_baseline_pytorch#383]
DG-Market的数据集格式需要怎么更改，望回复，十分感谢

**Comment by layumi** [comment]
下载下来，指定一下路径 https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L170 就行

**Comment by qiaosuobutouche** [comment]
> 下载下来，解压。 然后指定一下路径 https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L170 就行

作者您好，使用您的方法我成功的训练好了网络，请问在test环节，测试路径还使用原先的market1501数据集路径就可以把

**Comment by layumi** [comment]
@qiaosuobutouche  是的

**Comment by qiaosuobutouche** [comment]
> @qiaosuobutouche 是的

感谢回复，作者请问为什么我使用dg-market未加任何trick和market1501训练结果dgmarket就比1501的map提升了0.01，rank1甚至还下降了一点啊，这是为什么呢，都是20轮迭代

**Comment by layumi** [comment]
你好 

是的。 dgmarket 扩大了数据量，模型相对于 ood的情况会提升，对于 id的情况 帮助不明显。

**Comment by qiaosuobutouche** [comment]
> 

也就是在域内提升不明显，在迁移到别的项目时效果会更好吧
