### ISSUE TITLE
About PCB and Duke rank-1 accurate...

### ISSUE THREAD

**Issue by zengqixun123** [layumi/Person_reID_baseline_pytorch#39]
When I use PCB to train the model ,it always occurs error "out of memory",my GPU is 1080.How much memory do I need to train the model?or change the batchsize?

And when I train the Duke dataset, the train loss and the train accurate is quite small .But the final rank-1 is about 64%as you account.Does it mean overfitting ? what should I do if I want to increase the rank-1 in Duke dataset?

Thanks a lot!

**Comment by layumi** [comment]
Hi @zengqixun123 
Thanks for your attention

1. Actually I use P40 (16G Memory) for fast training. You may try using batchsize=16 or 8 (You may also need to chose a smaller learning rate). 
2. As for DukeMTMC-reID, you may check the issue https://github.com/layumi/Person_reID_baseline_pytorch/issues/32

**Comment by zengqixun123** [comment]
Thanks a lot ,it get correct result about 77% rank-1 and 59 map
