### ISSUE TITLE
Metric Learning method

### ISSUE THREAD

**Issue by Alommo** [layumi/Person_reID_baseline_pytorch#40]
Hi, @layumi
What's the metric learing method in your code? 
Thank you for much for your reply.

**Comment by layumi** [comment]
Yes, you are right.
Due to the nature of the softmax objective, the features of the same person share a small cosine distance.
So directly applying the cosine distance is sufficient for the person re-ID.

**Comment by Alommo** [comment]
Thanks a lot.
