### ISSUE TITLE
Number of classes

### ISSUE THREAD

**Issue by rhelck** [layumi/Person_reID_baseline_pytorch#412]
First of all, thank you for this project, its very cool.

I see that on the Market 1501 dataset, the number of classes is 751. If we apply a model trained on the Market 1501 dataset to a domain with a smaller number of classes (say, 3 people) will the results generalize?

**Comment by layumi** [comment]
Yes. @rhelck 
But I suggest you to try use more data, e.g., fusing Market, Duke and MSMT.

**Comment by rhelck** [comment]
@layumi I tested this in detail, and I understand that the model works well with a variable number of classes. Thank you for you response, as well as your contribution to open source code!
