### ISSUE TITLE
 filename = path.split('/')[-1] Raised ValueError in Windows Plateform

### ISSUE THREAD

**Issue by jpainam** [layumi/Person_reID_baseline_pytorch#42]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/c1ac81b88c92d2172673fb8fe67abef999559dfb/test.py#L146

This line causes error when using Windows Plateform
Kindly changed it to `filename = os.path.basename(path)`

**Comment by layumi** [comment]
Thank you @jpainam !
I have modified the `test.py`.
