### ISSUE TITLE
undefined symbol: cudnnSetConvolutionGroupCount

### ISSUE THREAD

**Issue by songning2018** [layumi/Person_reID_baseline_pytorch#44]
python: symbol lookup error: /home/sn/anaconda3/envs/pytorch0.3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudnnSetConvolutionGroupCount

I use python 3.6.2, pytorch0.3, numpy 1.14. 
I got the error when I run " python test.py --gpu_ids 0 --name /home/sn/person-reid/Person_reID_baseline_pytorch/model/ft_ResNet50 --test_dir /home/sn/person-reid/Market-1501/pytorch  --which_epoch 59".
Do you know how to solve this problem?

**Comment by layumi** [comment]
@songning2018 
It seems to be a error with cudnn.
You may try reinstalling the pytorch.
