### ISSUE TITLE
ValueError: expected 2D or 3D input (got 1D input)

### ISSUE THREAD

**Issue by GNAYUOHZ** [layumi/Person_reID_baseline_pytorch#49]
when I run train.py using resnet50,after running for sometime, I meet a problen of ValueError: expected 2D or 3D input (got 1D input),in  class ClassBlock(nn.Module):  def forward(self, x):  x = self.add_block(x).

**Comment by layumi** [comment]
Have you added this three lines?
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/train.py#L166-L168
It may be caused by batchnorm layer.

If the problem continues, do not hesitate to contact with me.

**Comment by GNAYUOHZ** [comment]
thank you very much. it helps me a lot
