### ISSUE TITLE
About out of memory error

### ISSUE THREAD

**Issue by moyans** [layumi/Person_reID_baseline_pytorch#5]
-------test-----------
64
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory

**Comment by moyans** [comment]
when I runing  test.py

**Comment by layumi** [comment]
You may change the batchszie from 64 to 32 or 16 in this line.
https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L71

**Comment by layumi** [comment]
I just added batchsize option to the latest version now.
You can directly use '--batchsize 16' in test.py.

**Comment by moyans** [comment]
get it, thanks.
