### ISSUE TITLE
KeyError: unexpected key in trained DenseNet model.

### ISSUE THREAD

**Issue by xuehaouwa** [layumi/Person_reID_baseline_pytorch#51]
When I try to use Trained DenseNet-121 model to get features, I got this error:  KeyError: 'unexpected key "model.fc.0.weight" in state_dict'.

Could you please tell me which part is wrong? 

Many thanks!

**Comment by layumi** [comment]
Hi @xuehaouwa ,
Sorry for that.
It is my old model which may be inconsistent with the current model structure.
If possible, I suggest you to train a new model.

**Comment by xuehaouwa** [comment]
Thanks, @layumi . It helps a lot.
