### ISSUE TITLE
Do the junk images also participate in re-ranking?

### ISSUE THREAD

**Issue by rocketbear** [layumi/Person_reID_baseline_pytorch#53]
It seems all the junk images are also used during the re-ranking process. But the problem is that for each query image, some of the junk images actually come from the same camera and may affect the retrieval performance if these junk images are used for re-ranking.

I want to know:
1. Do the junk images really participate in the re-ranking process?
2. If 1 is true, is it a widely accepted procedure in other published papers?

**Comment by layumi** [comment]
Hi @rocketbear 
Zhun @zhunzhong07 may answer you.

**Comment by zhunzhong07** [comment]
Hi, sorry for the late reply. We have two versions of re-ranking method, i.e. Matlabel and Python. For the original Matlab version, we use all the images (including junk images) for re-ranking. While in the python version, we discard the junk images from the gallery. These two versions achieve almost the same results. So you can either ignore or apply the junk images in the re-ranking process. However, we may not sure which image is junk image in the practice, so I advise to use all the images (including junk images) in the re-ranking process.
