### ISSUE TITLE
train出来rank1为什么才79？没有除以方差。

### ISSUE THREAD

**Issue by qw87494512** [layumi/Person_reID_baseline_pytorch#56]

**Comment by layumi** [comment]
Hi @qw87494512 
I do not understand that `you do not divide the std`. Why do you do that?

**Comment by layumi** [comment]
Cosine Distance is better for feature matching.
If you are interested in it, you may check the mechanism of Softmax Loss (and other softmax loss, such as sphere loss, large margin softmax loss, angular loss). 
Softmax Loss is close to the cosine distance.
