### ISSUE TITLE
I want to try whether the two pictures taken by my camera are the same person.what should i do?

### ISSUE THREAD

**Issue by 695874419** [layumi/Person_reID_baseline_pytorch#57]
I looked at the evaluate_gpu.py code. The code seems to match the image in the query with the image in the gallery. If I want to test the picture taken by my camera, do I need to create a new category in the gallery, then put some pictures in it, the same as query , create a new category and put some pictures in it? What if I don't know which category the query belongs to beforehand? and Are there any rules for the size of the gallery and query?

**Comment by layumi** [comment]
Hi @695874419 
You may check the code in https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/prepare.py#L13-L65
I prepare the data.

You should also take care for https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L145-L158
I get the label and camera ID.
