### ISSUE TITLE
 .jpg files not find

### ISSUE THREAD

**Issue by xiaoweihappy123** [layumi/Person_reID_baseline_pytorch#59]
net output size:
torch.Size([8, 751])
[Resize(size=(288, 144), interpolation=PIL.Image.BICUBIC), RandomCrop(size=(256, 128), padding=0), RandomHorizontalFlip(p=0.5), ToTensor(), Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])]
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    data_transforms['train'])
  File "/home/xiaowei/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/home/xiaowei/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 79, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /home/xiaowei/Person_reID_baseline_pytorch/market/pytorch/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

I do have images in my directory, the python version is 3.6, and the pytorch is 0.3.0.What's causing this?

**Comment by layumi** [comment]
Hi @xiaoweihappy123 
Could you check again your folder `/home/xiaowei/Person_reID_baseline_pytorch/market/pytorch/train`? Are there 751 folders (each folder contains image files)?

**Comment by xiaoweihappy123** [comment]
The market1501 dataset file I downloaded listed all the pictures and did not store them according to the ID.Do I need to do this by hand?

**Comment by xiaoweihappy123** [comment]
I But I've already run it

**Comment by layumi** [comment]
Is any error when you run `prepare.py`?
Could you check the output path in `prepare.py`? Do training images store in `/home/xiaowei/Person_reID_baseline_pytorch/market/pytorch/train`?

**Comment by xiaoweihappy123** [comment]
No any error. Is only creates several empty folders under the specified directory.

trian.py:default='/home/xiaowei/Person_reID_baseline_pytorch/market/pytorch'
prepare.py:download_path = '/home/xiaowei/Person_reID_baseline_pytorch/market'

What's the problem?

**Comment by layumi** [comment]
Have you unzipped the market1501 into this `download_path`?
Under `download_path`, there should be `bounding_box_train`, `bounding_box_test`, `bounding_box_query` ...

**Comment by xiaoweihappy123** [comment]
Yes, I've unzipped it. My classmate is also very helpless to this mistake.

**Comment by layumi** [comment]
Could you try `chmod -R 777 /home/xiaowei/Person_reID_baseline_pytorch/market`?

**Comment by xiaoweihappy123** [comment]
I just tried it but it didn't work

**Comment by layumi** [comment]
Is there any image under the `bounding_box_train`? 
There are no images under the `download_path/pytorch/train` ?

**Comment by xiaoweihappy123** [comment]
Both folders have images under them, and below "train" I added manually.

**Comment by Small93** [comment]
@xiaoweihappy123 i have the same problem， I have solved it. your path is wrong. /home/xiaowei/Person_reID_baseline_pytorch/market。
1、You must first download dataset(Market1501 Dataset)，and change the name of the database to 
market。
2、prepare.py: download_path = '/home/xiaowei/Person_reID_baseline_pytorch/market'
3、1 and 2 keep the name is the same(the name is market). use:
       python prepare.py
you will find many folder in the pytorch/train. and the other floders.

**Comment by xiaoweihappy123** [comment]
3q， I have solved it.
