### ISSUE TITLE
About input size of PCB

### ISSUE THREAD

**Issue by Simon4Yan** [layumi/Person_reID_baseline_pytorch#62]
Hello ZZD!

It is so glad to see your code including PCB structure. However, I have read PCB paper and noticed that the input size has been validated in the paper: the best choice is 384 times 128. But in your code the input size is: 392 times 192. https://github.com/layumi/Person_reID_baseline_pytorch/blob/60d39aa56f3d34bd5611c3e2cf4998e87ba94430/train.py#L79

**Comment by layumi** [comment]
Hi @Simon4Yan,  

Thank you.
Yes, you are right. I think the result is quit close, and easily to modify the code. 
So I didn't change the size for the time being.
