### ISSUE TITLE
运行 train。py时报错

### ISSUE THREAD

**Issue by TheBigCock** [layumi/Person_reID_baseline_pytorch#64]
您好，麻烦您有时间的话帮我解答以下问题！谢谢

请问运行程序train是出现以下错误是什么原因？
错误：urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by layumi** [comment]
When downloading the pretrained model, you need the access to the Internet.
