### ISSUE TITLE
how to get pedestrain tracking ids

### ISSUE THREAD

**Issue by sandhyalaxmi** [layumi/Person_reID_baseline_pytorch#69]
how can i use it for pedestrian tracking for my own video containing new persons

**Comment by sandhyalaxmi** [comment]
Thank you for your reply.
If a new person entered into video how can it knows whether the person existed or not?
is it useful for regression?

**Comment by layumi** [comment]
Hi @sandhyalaxmi 

When testing, you do not need to know who he is.

We only need pedestrian features and do the feature matching (this frame and last frame).
Since the feature is learned by discriminating different person (when training), it can perform well, even we directly apply it.

**Comment by sandhyalaxmi** [comment]
Thank you very much
