### ISSUE TITLE
PCB train

### ISSUE THREAD

**Issue by TingtingAlice** [layumi/Person_reID_baseline_pytorch#70]
when i run this command
`python train.py --PCB --batchsize 64 --name PCB-64`

it comes this error:
`Traceback (most recent call last):
  File "train.py", line 346, in <module>
    num_epochs=60)
  File "train.py", line 189, in train_model
    sm = nn.Softmax(dim=1)
TypeError: __init__() got an unexpected keyword argument 'dim'`

can you help me to fix that?

**Comment by layumi** [comment]
Hi @TingtingAlice 
Could you tell me your pytorch version?

**Comment by sandhyalaxmi** [comment]
run the command like this,
python3 train.py --gpu_ids 1 --name PCB --train_all --batchsize 32  --data_dir your_own_dataset  --erasing_p 0.5

**Comment by layumi** [comment]
```
import torch
print(torch.__version__)
```
