### ISSUE TITLE
could you upload pretrained model

### ISSUE THREAD

**Issue by whj363636** [layumi/Person_reID_baseline_pytorch#71]
Hi, would you please release the model you trained for these works?

Thanks a lot.

**Comment by layumi** [comment]
Hi @whj363636 

Sorry. Recently I am busy. 
My junior classmate  @dyh127 may help you. 

@dyh127  Could you upload your trained model? Thank you.

**Comment by LQNew** [comment]
Hello, @layumi , I also appreciate that you upload the pretrained models!
