### ISSUE TITLE
Question about evaluate.py

### ISSUE THREAD

**Issue by MasterofPLM** [layumi/Person_reID_baseline_pytorch#73]
In function evaluate(qf,ql,qc,gf,gl,gc), I have a question:

score = np.dot(gf,query) # calculate the distance
 # predict index
index = np.argsort(score)  #from small to large
index = index[::-1] #why reverse the index?

the index has show the order of distance from small to large, why reverse the index? Don't I get the farthest good index image as the rank result?

**Comment by layumi** [comment]
Hi @MasterofPLM ,  
I use cosine similarity. The large value indicates that the two images are similar.

**Comment by MasterofPLM** [comment]
> 
> 
> Hi @MasterofPLM ,
> I use cosine similarity. The large value indicates that the two images are similar.

Thanks!
