### ISSUE TITLE
re-ranking

### ISSUE THREAD

**Issue by LQ199302** [layumi/Person_reID_baseline_pytorch#74]
l tried the re-ranking to evaluate the result, however, it shows that rank-1 and mAP both are 0.0000. What can I do to obtain a good result

**Comment by LQ199302** [comment]
Thanks, and I use the re-ranking with PCB

**Comment by layumi** [comment]
@LQ199302  
The result without re-ranking is right?
Would you like to update your numpy and try again?

**Comment by 904281665** [comment]
Is your problem solved? I have the same problem.Thanks

**Comment by layumi** [comment]
Hi @904281665 
Could you provide more details? 
Do you use `--PCB`? Is mAP always 0?

**Comment by 904281665** [comment]
@layumi Thank you very much! I have sove this problem. I forgot to convert the label to numpy format. My fault. hahaha
