### ISSUE TITLE
torch.squeeze(x) might cause an error

### ISSUE THREAD

**Issue by hyk1996** [layumi/Person_reID_baseline_pytorch#77]
https://github.com/layumi/Person_reID_baseline_pytorch/blob/a8737ae88a36ac2ccd3c28688b73d6c65e741587/model.py#L74

Using torch.squeeze(x) might cause an error when x.shape = [1, 2048, 1, 1] (Sometimes there may be only one sample in the last batch of data loader).
Replacing  `x = torch.squeeze(x)`  with  `x = x.view(x.size(0), -1)`  will be better.

**Comment by layumi** [comment]
Thank you. You are right. I will modify the code later.
