### ISSUE TITLE
请问train.py中，输入图片经过ImageFolder和DataLoader后的格式是什么

### ISSUE THREAD

**Issue by yaodonggggggg** [layumi/Person_reID_baseline_pytorch#83]
ImageFolder在108行
DataLoader在113行
再到167行for data in dataloaders[phase]:
                   # get the inputs
                   inputs, labels = data
这个的data是以什么形式存在的？怎么会有两个值，一个图片一个标记？

**Comment by layumi** [comment]
tuple
You may use `type()` to see the datatype in python.

**Comment by yaodonggggggg** [comment]
> tuple
> You may use `type()` to see the datatype in python.

谢谢，之前用type（）老有error，可能使用方式有问题
