### ISSUE TITLE
RuntimeError when running test.py

### ISSUE THREAD

**Issue by maomaochongchh** [layumi/Person_reID_baseline_pytorch#84]
Hi, @layumi. Thanks for the great code. 
I run successfully based on ResNet50.  After i trained the model based on Densenet121, when running test.py I got such errors as below:
`
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7ff728286d50>> ignored
Traceback (most recent call last):
  File "/home/chh/Code/Person_reID_baseline_pytorch-master/test.py", line 162, in <module>
    gallery_feature = extract_feature(model, dataloaders['gallery'])
  File "/home/chh/Code/Person_reID_baseline_pytorch-master/test.py", line 112, in extract_feature
    outputs = model(input_img) 
......
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
`
I found that when i=0, it was normal, but when i=1, the Error happened in test.py#L128 ：
`       
 for i in range(2):
            if(i==1):
                img = fliplr(img)
            input_img = Variable(img.cuda())
            outputs = model(input_img) 
            f = outputs.data.cpu()
            #print(f.size())
            ff = ff+f
`

**Comment by layumi** [comment]
out of memory 
Could you try `python test.py --batchsize 16`?

**Comment by maomaochongchh** [comment]
Thanks for your reply. It works. just because the model's parameters take up a lot of storage ?
