### ISSUE TITLE
mAP的计算方式是怎么样的？

### ISSUE THREAD

**Issue by wangyujie413** [layumi/Person_reID_baseline_pytorch#85]
按照[https://bbs.csdn.net/topics/392326863](url)提到的mAP计算方式，我认为
`def compute_mAP(index, good_index, junk_index):
......
    for i in range(ngood):
        d_recall = 1.0/ngood
        precision = (i+1)*1.0/(rows_good[i]+1)
        if rows_good[i]!=0:
            old_precision = i*1.0/rows_good[i]
        else:
            old_precision=1.0
        ap = ap + d_recall*(old_precision + precision)/2`
中只需要`precision = (i+1)*1.0/(rows_good[i]+1)`即可。
请问您的这种计算方式是按什么公式得到的？

**Comment by layumi** [comment]
@wangyujie413 ,
It is based on the same algorithm. (http://www.robots.ox.ac.uk/~vgg/data/oxbuildings/compute_ap.cpp)
In the original code, the `for` loop is too slow. **In fact, the value of map only changed when it meets the true-matches.** So I optimize the original evaluation code to a more efficient manner.
