### ISSUE TITLE
About the way you get the features!

### ISSUE THREAD

**Issue by maomaochongchh** [layumi/Person_reID_baseline_pytorch#86]
Sorry, why do yo get the features by adding the features of raw and flipped images in the test.py?
`
        for i in range(2):
            if(i==1):
                img = fliplr(img)
            input_img = Variable(img.cuda())
            outputs = model(input_img) 
            f = outputs.data.cpu()
            #print(f.size())
            ff = ff+f
`

**Comment by layumi** [comment]
Yes. It is a small trick to improve the performance.
