### ISSUE TITLE
PCB implementation 

### ISSUE THREAD

**Issue by hfutzzw** [layumi/Person_reID_baseline_pytorch#87]
Hi, thanks you for your simple but great work,
and I notice that a small difference between original paper and your implementation about PCB
paper use **1x1 conv** for channel reduction,
your implementation use FC layer,
The difference between two tasks was share parameters among 6 parts or not, does it affect result?
and I expect to see RPP added, thank you!

**Comment by layumi** [comment]
Hi @hfutzzw ,
1. 1x1 conv equals to linear layer. There are not significant differences.

2. I use six different linear layers.  Using shared weight will compromise the result.

I will consider to add rpp in the future. Thank you.
