### ISSUE TITLE
matconvnet implement

### ISSUE THREAD

**Issue by lirui111** [layumi/Person_reID_baseline_pytorch#88]
l tried using the matconvnet to implement this code, however, it shows that rank-1 only 61.5 and mAP 36.3 (market501，single-query) . I use the same setting with yours but that has little effect on the result. What can I do to obtain a good result？
Thanks a lot！

**Comment by layumi** [comment]
Hi @lirui111 
Did you use my code? 
Please check https://github.com/layumi/Person_reID_baseline_matconvnet
