### ISSUE TITLE
RandomErasing

### ISSUE THREAD

**Issue by Play2Boy** [layumi/Person_reID_baseline_pytorch#9]
问题1：文章中说的是用随机值填充，代码给的均值是统计得到的吗？
问题2：对应这种global represention用这种方法可能有效，但是针对part-based方法，反倒丢失了细节，不知是否可行？

**Comment by layumi** [comment]
Hi @Play2Boy 
Zhun @zhunzhong07 will answer your question.

**Comment by zhunzhong07** [comment]
Hi, @Play2Boy it is the ImageNet mean value,  erasing with random values achieves approximately
equal performance to the ImageNet mean pixel value.

**Comment by Play2Boy** [comment]
hahahaha，thanks！
