### ISSUE TITLE
model.model.fc.parameters()

### ISSUE THREAD

**Issue by distant1219** [layumi/Person_reID_baseline_pytorch#90]
In `train.py`,  the code is:
```
optimizer_ft = optim.SGD([
             {'params': base_params, 'lr': 0.01},
             {'params': model.model.fc.parameters(), 'lr': 0.1},
             {'params': model.classifier.parameters(), 'lr': 0.1}
         ], weight_decay=5e-4, momentum=0.9, nesterov=True)
```

but in the class `ft_net` of  `model.py`, you don't use the fc layer, I wonder that  why  you optim this fc layer's parameters in train phase.

**Comment by layumi** [comment]
Yes.  You are right.
I will consider to remove `model.model.fc.parameters()`, though it does not affect the training.
