### ISSUE TITLE
可否用于除人之外其他类别物体的匹配呢？

### ISSUE THREAD

**Issue by nationalflag** [layumi/Person_reID_baseline_pytorch#91]

**Comment by layumi** [comment]
Hi @nationalflag 
Sure. You may try bird retrieval (training on first 200 classes and test on the rest)  [this paper](https://arxiv.org/abs/1511.06452)
or Oxford building retrieval (training on a dataset proposed on ECCV and test on the Oxford 5k). You may check [this paper](https://arxiv.org/pdf/1611.05666.pdf).
