### ISSUE TITLE
NameError: name 'network_to_half' is not defined

### ISSUE THREAD

**Issue by xxx2974** [layumi/Person_reID_baseline_pytorch#96]
when I test with python test.py --gpu_ids 0 --name ft_ResNet50 --test_dir Dataset/Market/pytorch  --batchsize 32 --which_epoch 59 --PCB

error:
NameError: name 'network_to_half' is not defined

how can I solve it?

**Comment by layumi** [comment]
Have you installed apex?
```bash
git clone https://github.com/NVIDIA/apex.git
python setup.py install --cuda_ext --cpp_ext
```

**Comment by xxx2974** [comment]
ok,but when I install the apex with "python setup.py install --cuda_ext --cpp_ext",I got the other error:
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xiaozhenzhen/anaconda2/envs/pytorch-pcb/lib/python3.6/site-packages/torch/lib/include -I/home/xiaozhenzhen/anaconda2/envs/pytorch-pcb/lib/python3.6/site-packages/torch/lib/include/TH -I/home/xiaozhenzhen/anaconda2/envs/pytorch-pcb/lib/python3.6/site-packages/torch/lib/include/THC -I/home/xiaozhenzhen/anaconda2/envs/pytorch-pcb/include/python3.6m -c csrc/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.6/csrc/flatten_unflatten.o -DTORCH_EXTENSION_NAME=apex_C -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
csrc/flatten_unflatten.cpp:1:29: fatal error: torch/extension.h: 没有那个文件或目录
compilation terminated.
error: command 'gcc' failed with exit status 1
@layumi

**Comment by layumi** [comment]
What is the version of your pytorch?

**Comment by xxx2974** [comment]
The version is 0.3,and python is 2.7

**Comment by xxx2974** [comment]
sorry  pytorch verson is 0.4 and python is 3.6

**Comment by layumi** [comment]
Could you try to update your pytorch to 1.0?
Apex is recommended to be used with pytorch 1.0

**Comment by xxx2974** [comment]
OK,thanks,I will have a try.

**Comment by xxx2974** [comment]
Excuse me! Will the part of "RPP" be included in the project? @layumi

**Comment by layumi** [comment]
@xxx2974 
Not for the time being. I will take a look.

**Comment by d-li14** [comment]
@layumi I wonder if it is necessary to convert the PCB model to float16 during testing. As in your code, this conversion is mandatory.

**Comment by layumi** [comment]
Hi @d-li14 
The model is saved in the fp16 form. So I load it as the fp16 precision.

**Comment by d-li14** [comment]
@layumi But it seems `fp16: false` in the `opts.yaml` for the PCB model you provided (https://github.com/layumi/Person_reID_baseline_pytorch#trained-model), and I have also successfully tested the downloaded model by removing this line https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/test.py#L214

**Comment by layumi** [comment]
@d-li14 
In the trained model, I do not use fp16 to train the PCB model. fp16 =False. 
So when you test the PCB model, I think it will not run the `network_to_half ` . The trained PCB model should run in fp32 precision when testing.

Or could you show me your error info?

**Comment by d-li14** [comment]
@layumi OK, thanks for fixing!
