### ISSUE TITLE
Do i ready need cuda version ?

### ISSUE THREAD

**Issue by zhongsb** [layumi/Person_reID_baseline_pytorch#97]
I have version : 
1、pytorch-cpu   1.0.0
2、python 3.6
3、torchvision-cpu    0.2.1

and when i run 

`python train.py --gpu_ids 0 --name ft_ResNet50 --train_all --batchsize 32  --data_dir ../Market/pytorch`

i got an error

`Traceback (most recent call last):
  File "train.py", line 60, in <module>
    torch.cuda.set_device(gpu_ids[0])
  File "D:\program\Anaconda\envs\py36\lib\site-packages\torch\cuda\__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'`

so , what's the problem ? do i need a pytorch version for cuda ?

**Comment by layumi** [comment]
@zhongsb 
Cuda 10 is good if your gpu support the cuda10.

**Comment by lzzlxxlsz** [comment]
have you solved this problem?is cuda needed for the cpu
