### ISSUE TITLE
flip horizontal in extract_feature

### ISSUE THREAD

**Issue by hehedawang** [layumi/Person_reID_baseline_pytorch#99]
in test.py, each image is computed twice in the extract_feature function with a flip horizontal operation. Is it necessary? It's unusual in other projects. Can you explain the meaning? Thanks!!!
![2019-01-08 15-20-14](https://user-images.githubusercontent.com/30236151/50816068-6391e180-135a-11e9-93d4-98c6c9b8ca1c.png)

**Comment by layumi** [comment]
Hi @hehedawang ,

Sorry for the late response. It is a trick and not so necessary.
If you check the paper, e.g., ResNet-50, Kaiming etal. also applied a crop-10 policy to improve the classification result. It also is not necessary.

The main reason is the mean of more inputs is relatively stable. We hope flip the input can result a relatively-robust feature.
